### PR TITLE
Doc strings for solvers 

### PR DESCRIPTION
**Pull request by AnasAbdelR**
Got started on adding the doc strings, wanted to make a draft PR so you can see how I am doing them so far. Some of them had papers but their names were ambiguous in terms of how many of the structs below were part of the reference. I made a separate docstring for each in those cases - i'll keep chipping at this if everything is okay so far

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
That looks good

**Comment by AnasAbdelR** [comment]
So the pipeline errors in that situation
"""
Julien Berland, Christophe Bogey, Christophe Bailly. Low-Dissipation and Low-Dispersion
Fourth-Order Runge-Kutta Algorithm. Computers & Fluids, 35(10), pp 1459-1463, 2006.
doi: https://doi.org/10.1016/j.compfluid.2005.04.003
"""
"""
RK46NL: 6-stage, fourth order low-stage, low-dissipation, low-dispersion scheme.
        Fixed timestep only.
"""

Guess I can't have a separate docstring. Just join it and if the alg isn't actually referenced there it's okay?

**Comment by ChrisRackauckas** [comment]
Yeah just join them

**Comment by AnasAbdelR** [comment]
With all that endless scrolling I didn't expect to finish by today, but I've reached the end of OrdinaryDiffEq xD

**Comment by ChrisRackauckas** [comment]
Now the other packages? 😅

**Comment by AnasAbdelR** [comment]
Hahaha, I gotchu, just list the the ones that need it and i'll track them down asap

**Comment by ChrisRackauckas** [comment]
They all need it, but copying over some of the Sundials details for CVODE and IDA is probably the most relevant, along with ODEInterfaceDiffEq.jl

**Pull request merged**
