### PR TITLE
Make W_transform always true

### PR DESCRIPTION
**Pull request by oscardssmith**
Rosenbrock23 and Rosenbrock32 need updating to the W_transform versions, but other than that, this PR removes ~200 lines of complexity for free.

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Yeah this is a good idea. The same would need to be done on StochasticDiffEq for this to go through.

**Comment by oscardssmith** [comment]
Now that Rosenbrock23 is updated, I think this should be ready to go. Let's see if CI agrees.

**Comment by oscardssmith** [comment]
ah it looks like ODEExtrapolation also is currently written with transform false.

**Comment by oscardssmith** [comment]
CI green. Merge?

**Review by ChrisRackauckas — APPROVED** [review]

**Pull request merged**
