### PR TITLE
Fix missing and incorrect uses of `unwrap_alg` in `perform_step!`

### PR DESCRIPTION
**Pull request by danielwe**
I took a comprehensive approach to fixing #1618. I'm not equally confident in all of the changes so feel free to pick and choose commits. There are also potential issues that I wasn't certain enough to do something about at all, see below. Feedback appreciated.

**Summary**

* Added missing `unwrap_alg` calls to make all RKC methods, including ROCK4, work in composite algorithms (`is_stiff = true`)
* Same for `QNDF` (`is_stiff = true`)
* Same for all extrapolation methods (`is_stiff = false` for explicit methods, `is_stiff = true` for implicit methods including the undocumented `ImplicitEulerBarycentricExtrapolation`)
* Same for Anas5, KuttaPRK2p5, and PDIRK44 (`is_stiff = false` for Anas5 and KuttaPRK2p5, `is_stiff = true` for PDIRK44)
* Changed `is_stiff` from `true` to `false` for FRK65 and PFRK87 (both are listed as non-stiff in the docs)
* Removed a bunch of redundant unpackings of `alg`, mostly from Lie group and DAE methods but also a couple from RKC methods

Here are the remaining methods that still reference `integrator.alg` directly and are thus incompatible with any form of `CompositeAlgorithm`:

* FunctionMap
* ExplicitRK
* McAte42 (will fail silently when part of a CompositeAlgorithm---it's just a branch adding extra steps `if typeof(integrator.alg) <: McAte42`)
* CNAB2, CNLF2, and SBDF
* Every Krylov-enabled Lie group solver _except_ LinearExponential
  * Full list: MagnusMidpoint, LieRK4, RKMK4, RKMK2, MagnusNC8, MagnusGL4, MagnusGL8, MagnusNC6, MagnusGL6, MagnusGauss4, LieEuler, MagnusLeapfrog 

Things that kinda seem wrong to me but I wasn't sure:

* LinearExponential calls `unwrap_alg(integrator, true)`, i.e., it claims to be a stiff algorithm. This is the exact solver for LTI systems. Does this make sense at all? 

**Questions/TL;DR**

* Was I correct assuming that it's a bug for FRK65 and PFRK87 to identify as stiff?
* Do any of the following have good choices for `is_stiff` or should they remain uncomposable?
  * FunctionMap (wouldn't ever make sense to compose would it?)
  * ExplicitRK (general, takes tableau, so probably can't make such an assumption?)
  * McAte42 (symplectic, perhaps that's too specialized for composition anyway, but also I'm guessing `false`?)
  * CNAB2, CNLF2, SBDF (split solvers, perhaps don't make much sense to compose but also probably `true`?)
  * Lie group solvers
* Should LinearExponential really identify as stiff?
* Would it make sense to do `unwrap_alg(integrator, nothing)` for algorithms that aren't unambiguously stiff or non-stiff (ExplicitRK, perhaps Lie group solvers?)? That way they could still participate in custom CompositeAlgorithms, just not the built-in stiffness-based autoswitching, and one could make `unwrap_alg` throw a friendly, descriptive error about the latter.

Apologies for handing out lots of work with all the recent PRs---please take it as a sign of appreciation of this package.

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
> including the undocumented ImplicitEulerBarycentricExtrapolation

@utkarsh530 can you add documentation for this one? Nice catch @danielwe

**Comment by ChrisRackauckas** [comment]
> ExplicitRK

Most of that exclusion list looks about right, but this one seems like an exception. You should be able to make the generic explicit RK work with this though. At least let's get an issue open for it.

**Comment by ChrisRackauckas** [comment]
> LinearExponential calls unwrap_alg(integrator, true), i.e., it claims to be a stiff algorithm. This is the exact solver for LTI systems. Does this make sense at all?

Ehh, this really is quite an exception since it fails except in the specific case where it's an analytical solution, so yeah... I don't think there's ever a reason to autoswitch, but we might as well label it like the other exponential integrators for continuity.

**Comment by ChrisRackauckas** [comment]
> Was I correct assuming that it's a bug for FRK65 and PFRK87 to identify as stiff?

They are non-stiff.

> Would it make sense to do unwrap_alg(integrator, nothing) for algorithms that aren't unambiguously stiff or non-stiff (ExplicitRK, perhaps Lie group solvers?)? That way they could still participate in custom CompositeAlgorithms, just not the built-in stiffness-based autoswitching, and one could make unwrap_alg throw a friendly, descriptive error about the latter.

That would probably be nice. Better errors are always helpful!

**Comment by danielwe** [comment]
Thanks for the feedback. Changes made:

* `unwrap_alg` throws descriptive error if `integrator.alg` is an AutoSwitch and `is_stiff = nothing`
* `unwrap_alg(integrator, nothing)` now used for the remaining algorithms that need access to `alg`: FunctionMap, ExplicitRK, McAte42, SBDF, and all exponential solvers including LinearExponential
* Never mind CNAB2 and CNLF2, they didn't need `alg` and the redundant unpacking has been removed

Requesting final confirmation that `is_stiff = nothing` is the right call for symplectic integrators (McAte42) and SBDF. Wondering if one could also argue in favor of `false` and `true`, respectively.

**Comment by ChrisRackauckas** [comment]
symplectic integrators are only non-stiff. Ever using autoswitch would make it non-symplectic though since it's a global not a local property. SBDF is for stiff equations (or semi-stiff because of IMEX)

**Comment by danielwe** [comment]
Yes, exactly. There! (I know it makes no sense to autoswitch so this is entirely inconsequential, but might as well make it as consistent as it can get.)

**Comment by ChrisRackauckas** [comment]
Yeah, might as well let people explore. Who knows what they will find!

**Pull request merged**
