### PR TITLE
Improve inference with vectorcontinuouscallbacks

### PR DESCRIPTION
**Pull request by ChrisRackauckas**
This is the final part of the solution to https://discourse.julialang.org/t/significant-allocations-with-callbacks-tsit5/66467, except for a phantom bug:

https://github.com/JuliaLang/julia/issues/35800

where revising the code is required for inference specialization...

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
bizarre_allocations

**Comment by ChrisRackauckas** [comment]
Related to https://github.com/SciML/DifferentialEquations.jl/issues/786 on callbacks.

**Comment by helengracehuang** [comment]
Is there any update on this issue with the recent updates in JuliaLang?

**Comment by ChrisRackauckas** [comment]
Apparently one of the precompilation changes might fix it: https://github.com/JuliaLang/julia/pull/43990#issuecomment-1040652434

**Pull request merged**
