### PR TITLE
Fix tests in ImplicitEulerExtrapolation

### PR DESCRIPTION
**Pull request by utkarsh530**
Hi, I was checking implementation changes in ImplicitEulerExtrapolation, the current master tests were failing https://gitlab.com/JuliaGPU/OrdinaryDiffEq.jl/-/jobs/676218514. I have updated them. I also reflected the changes in out-of-place version too.
@ChrisRackauckas @kanav99 please have a look.

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
That looks reasonable. Are the GPU tests not running?

**Comment by utkarsh530** [comment]
It won't run on PRs created on other forks; some Gitlab issue was there as mentioned by you. So yeah I had to checked afterwards in the master and tests was failing.

**Comment by ChrisRackauckas** [comment]
I see. We might want to get a version of the extrapolation methods running on Travis anyways: it doesn't all have to be multithreaded.

**Comment by utkarsh530** [comment]
Yeah, that would be a good idea for other contributors as well.

**Comment by utkarsh530** [comment]
@ChrisRackauckas I have added ODE Extrapolation tests in Travis. Let me if there are any other changes to be made before merging.

**Comment by ChrisRackauckas** [comment]
https://travis-ci.org/github/SciML/OrdinaryDiffEq.jl/jobs/716290143#L1007 looks like they don't pass.

**Comment by utkarsh530** [comment]
Yeah, a typo was there, my bad.

**Pull request merged**
