### PR TITLE
use SnoopPrecompile.@precompile_setup

### PR DESCRIPTION
**Pull request by aviatesk**
This allows us to turn off precompilation of OrdinaryDiffEq via Preferences.jl

### CODE REVIEW

**Comment by aviatesk** [comment]
By wrapping the precompilation workload by `SnoopPrecompile.@precompile_setup`, we can turn off the precompilation via Preferences.jl.
For example, you can have `LocalPreferences.toml` at the root of the project with the following contents
```toml
[SnoopPrecompile]
skip_precompile = ["OrdinaryDiffEq"]
```
and then the precompilation will be turned off. This setting can be useful when we develop OrdinaryDiffEq or a parent package using it since precompiling OrdinaryDiffEq takes quite some time.

**Comment by ChrisRackauckas** [comment]
But you could've already done that before with the more refined precompilation controls? I guess having another way to do it is fine. Can you add this to the documentation page on precompilation controls in DiffEqDocs?

**Comment by aviatesk** [comment]
> But you could've already done that before with the more refined precompilation controls?

Yes, we can always edit the package file directly. The Preferences.jl approach is more useful when we develop a package that has OrdinaryDiffEq.jl as its dependency, since it allows us to turn of the compilation of this package just by placing `LocalPreferences.toml` on the parent package directly.

> Can you add this to the documentation page on precompilation controls in DiffEqDocs?

Yeah, but I guess OrdinaryDiffEq/docs is the better place for that?

**Comment by ChrisRackauckas** [comment]
> The Preferences.jl approach is more useful when we develop a package that has OrdinaryDiffEq.jl as its dependency, since it allows us to turn of the compilation of this package just by placing LocalPreferences.toml on the parent package directly.

That doesn't answer the question though, since it's still Preferences.

> Yeah, but I guess OrdinaryDiffEq/docs is the better place for that?

But the old docs also need to be updated.

**Comment by aviatesk** [comment]
> That doesn't answer the question though, since it's still Preferences.

I'm not sure I understand the question. SnoopPrecompile automatically loads Preferences.jl and looks for configurations specified in LocalPreferences.toml when a package that uses SnoopPrecompile is precompiled.

> But the old docs also need to be updated.

Okay, I will submit a PR to DiffEqDocs.jl too. I will push a commit that update this package's `docs` quickly.

**Comment by aviatesk** [comment]
Wow, it looks like SciML's documentation is even more sophisticatedly structured than I anticipated. It seems like we just need to update DiffEqDocs. I believe that this pull request is good to go as it stands.

**Comment by aviatesk** [comment]
@ChrisRackauckas bump?

**Comment by ChrisRackauckas** [comment]
I don't recall seeing the DiffEqDocs PR?

**Comment by ChrisRackauckas** [comment]
I don't recall seeing the DiffEqDocs PR?

**Comment by ChrisRackauckas** [comment]
@oscardssmith is there something to update from this?

**Comment by oscardssmith** [comment]
I think this can just be closed, but ideally @aviatesk would confirm.

**Pull request closed without merging**
