### PR TITLE
Rework CI to build on the Gitlab templates.

### PR DESCRIPTION
**Pull request by maleadt**
Fixes ARM testing (or at least the job submission part of that).

### CODE REVIEW

**Comment by maleadt** [comment]
@ChrisRackauckas Is your runner using Docker, or does it just execute on the system?

**Comment by ChrisRackauckas** [comment]
That's a question for @yingboma

**Comment by YingboMa** [comment]
It is just using the shell.

**Comment by maleadt** [comment]
Hm, why isn't this picking up jobs for your p6000 runner. This does not seem related to these changes; other builds in the pipeline are stuck too. Is the runner up?

**Comment by maleadt** [comment]
```
$ apt-get -qq update
00:01
E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)
E: Unable to lock directory /var/lib/apt/lists/
W: Problem unlinking the file /var/cache/apt/pkgcache.bin - RemoveCaches (13: Permission denied)
W: Problem unlinking the file /var/cache/apt/srcpkgcache.bin - RemoveCaches (13: Permission denied)
```

The Gitlab templates assume root, which is easy when running in Docker. @YingboMa, you mentioned you had a Docker-based runner set up, what's its tag?

**Pull request closed without merging**
