### PR TITLE
abstractdiffeqop -> abstractscimlop

### PR DESCRIPTION
**Pull request by vpuri3**
change `AbstractDiffEqLinearOperator, AbstractDiffEqOperator` to `AbstractSciMLOperator`

did just enough in this PR to fix error in https://github.com/SciML/DiffEqBase.jl/pull/870

### CODE REVIEW

**Review by ChrisRackauckas — APPROVED** [review]

**Comment by ChrisRackauckas** [comment]
> did just enough in this PR to fix error in https://github.com/SciML/DiffEqBase.jl/pull/870

Then make sure to weak dep this bump in that PR.

**Comment by vpuri3** [comment]
@ChrisRackauckas merge?

**Comment by ChrisRackauckas** [comment]
Some tests were not properly updated: https://github.com/SciML/OrdinaryDiffEq.jl/actions/runs/4099781298/jobs/7070003299#step:6:549

That test should probably use a MatrixOperator.

**Comment by vpuri3** [comment]
just burnt 2hrs on this - changing to `MatrixOperator` at this point is leading to errors in many different places. Some of those errors are cropping up because we haven't changed to SciMLOps in `DiffEqBase` yet, and are fixed  when I ran with https://github.com/SciML/DiffEqBase.jl/pull/870 version of `DiffEqBase`.

for now, I am just going to resolve the method ambiguity and chug along. We will make more changes to OrdinaryDiffEq.jl later.

**Comment by vpuri3** [comment]
rerunning CI after SciMLBase merge

**Comment by vpuri3** [comment]
ok it's picking up SciMLBase 1.8.3. lets see if the test passes

**Comment by vpuri3** [comment]
@ChrisRackauckas this is good to go

**Comment by ChrisRackauckas** [comment]
Still needs about half of the tests to run.

**Pull request merged**
