### PR TITLE
No need to depend on LV

### PR DESCRIPTION
**Pull request by chriselrod**
I am not sure why the diff of `Project.toml` is reported here as being so large. Locally, I get
```sh
> g d
Project.toml --- 1/2 --- TOML
23 23 LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
24 24 LinearSolve = "7ed4a6bd-45f5-4d41-b270-4a48e9bafcae"
25 25 Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
26 .. LoopVectorization = "bdcacae8-1622-11e9-2a5c-532679323890"
27 26 MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
28 27 MuladdMacro = "46d2c3a1-f734-5fdb-9937-b9b9aeba4221"
29 28 NonlinearSolve = "8913a72c-1f9b-4ce2-8d82-65094dcecaec"

Project.toml --- 2/2 --- TOML
63 62 LinearAlgebra = "1.9"
64 63 LinearSolve = "2.1.10"
65 64 Logging = "1.9"
66 .. LoopVectorization = "0.12"
67 65 MacroTools = "0.5"
68 66 MuladdMacro = "0.2.1"
69 67 NLsolve = "4"

src/OrdinaryDiffEq.jl --- Text (22 errors, exceeded DFT_PARSE_ERROR_LIMIT)
18 18 
19 19 using LinearAlgebra
20 20 
21 .. using LoopVectorization
22 .. 
23 21 import StaticArrayInterface
24 22 
```

### CODE REVIEW

**Comment by chriselrod** [comment]
Running the formatter results in a very large diff. Maybe I'm on a different version of the formatter, or it hasn't been run in a long time?

**Comment by ChrisRackauckas** [comment]
The formatter still has some issues that haven't been addressed so it's effectively disabled for now. Don't worry about that

**Review by ChrisRackauckas — APPROVED** [review]

**Comment by ChrisRackauckas** [comment]
Maybe it's a line endings thing?

**Comment by chriselrod** [comment]
> Maybe it's a line endings thing?

Yeah, could be a windows-> linux line ending change.

**Pull request merged**
