### PR TITLE
Unnecessary type promotion causes issues with Callbacks  + Tracker

### PR DESCRIPTION
**Pull request by avik-pal**

### CODE REVIEW

**Comment by devmotion** [comment]
Downstream test errors should be fixed by https://github.com/SciML/ODEInterfaceDiffEq.jl/pull/38.

**Comment by ChrisRackauckas** [comment]
Can we get a test with Callbacks + Tracker? That is an important one and seems to have previously dodged our tests.

**Comment by devmotion** [comment]
> Downstream test errors should be fixed by SciML/ODEInterfaceDiffEq.jl#38.

Fixed the DataStructures incompatibility of OrdinaryDiffEq but tests still fail since GPU packages are not compatible with DataStructures.

**Comment by devmotion** [comment]
More precisely, the latest releases of GPUCompiler and CUDA are compatible with DataStructures 0.18 but the latest release of CUDA is not compatible with the latest release of GPUCompiler. It's fixed in the master branch, so CUDA just needs a new release.

**Comment by avik-pal** [comment]
> Can we get a test with Callbacks + Tracker? That is an important one and seems to have previously dodged our tests.

Sure. I will add that.

**Comment by DhairyaLGandhi** [comment]
Can you check for the DataStructures.jl compat issue now? Updating to GPUCompiler@0.6.1 should unblock things.

**Pull request merged**
