### PR TITLE
Update step-sizing in Implicit Euler Extrapolation

### PR DESCRIPTION
**Pull request by utkarsh530**
Hi, I have updated `ImplicitEulerExtrapolation` with Hairer Wanner Adaptivity as written previously. The results are much better, but as I suggested earlier, it would be beneficial if we use barycentric extrapolation instead of Richardson's extrapolation. However, I made these changes earlier with Richardson's extrapolation and we could decide and review these changes. I feel that we should implement barycentric extrapolation from Implicit Euler from scratch because it would result in our caches being optimised and better control rather altering the previous one. What are your views? Maybe we could keep them both.

@ChrisRackauckas @kanav99 could you please share your thoughts on how to proceed and review this?

### CODE REVIEW

**Comment by utkarsh530** [comment]
Results:
ROBER
Before:
```
julia> sol = solve(prob,ImplicitEulerExtrapolation())
┌ Warning: Threading in `ImplicitEulerExtrapolation` is currently disabled. Thus `threading` has been changed from `true` to `false`.
└ @ OrdinaryDiffEq C:\Users\Utkarsh\.julia\dev\OrdinaryDiffEq\src\algorithms.jl:79
retcode: Success
Interpolation: 3rd order Hermite
t: 1480-element Array{Float64,1}:
      0.0
      0.000532175305206701
      0.0007867115380990222
      0.0010487682235895987
      0.0013266597226664375
      0.0016459299286835803
      0.0020416400015740234
      0.0025804697353095044
      0.0034161545162038854
      0.005023219364980107
      0.010570723919425758
      0.018917075865784266
      0.031168677360687166
      ⋮
  98586.75617460939
  98720.7207032461
  98854.77892840243
  98988.93085337573
  99123.17649027564
  99257.5158422426
  99391.94893015099
  99526.47574808092
  99661.09629893076
  99795.81059444192
  99930.61864628944
 100000.0
u: 1480-element Array{Array{Float64,1},1}:
 [1.0, 0.0, 0.0]
 [0.9999787132143604, 1.9478665298433788e-5, 1.8085734662215262e-6]
 [0.9999685321982339, 2.5658441394859306e-5, 4.292830709899764e-6]
 [0.9999580507914484, 2.993511517683831e-5, 9.151690956038029e-6]
 [0.9999469367614029, 3.273975939368385e-5, 1.6419280733108374e-5]
 [0.9999341690141186, 3.454956582840822e-5, 2.658058894290249e-5]
 [0.9999183464500588, 3.5641475162828294e-5, 4.073129502615469e-5]
 [0.999896805135541, 3.6216612095915396e-5, 6.131765202597862e-5]
 [0.9998634053882459, 3.644501814686977e-5, 9.429512707069117e-5]
 [0.9997992077080006, 3.648737622648834e-5, 0.00015840657263297342]
 [0.9995779213659741, 3.6454198337689344e-5, 0.0003798169931636322]
 [0.9992459240983853, 3.639660480980597e-5, 0.0007120454984350466]
 [0.9987606037970733, 3.631259453864171e-5, 0.0011977471065830277]
 ⋮
 [0.1023867352428024, 2.6531107375724847e-7, 1.5441898895963657]
 [0.10234163590887091, 2.651456791001035e-7, 1.5444722380423686]
 [0.10229658742357871, 2.6498050317556024e-7, 1.5447544321763054]
 [0.10225158969658944, 2.6481554554599706e-7, 1.5450364721973076]
 [0.10220664263723854, 2.6465080577272586e-7, 1.5453183583226164]
 [0.10216174615563814, 2.644862834182006e-7, 1.5456000907501997]
 [0.10211690016102279, 2.643219780438974e-7, 1.5458816697147755]
 [0.10207210456450279, 2.641578892146407e-7, 1.5461630953944776]
 [0.10202735927685615, 2.639940165012107e-7, 1.5464443679855564]
 [0.10198266420853318, 2.6383035947096253e-7, 1.5467254877023318]
 [0.10193801927020739, 2.6366691769012286e-7, 1.5470064547585263]
 [0.10189957816039436, 2.635138834735852e-7, 1.5471508945632937]
```
After:
```
julia> sol = solve(prob,ImplicitEulerExtrapolation())
┌ Warning: Threading in `ImplicitEulerExtrapolation` is currently disabled. Thus `threading` has been changed from `true` to `false`.
└ @ OrdinaryDiffEq C:\Users\Utkarsh\.julia\dev\OrdinaryDiffEq\src\algorithms.jl:83
retcode: Success
Interpolation: 3rd order Hermite
t: 741-element Array{Float64,1}:
      0.0
      0.001363507285173949
      0.0032939954615697925
      0.010285519301538147
      0.026702539030171668
      0.058402368675613145
      0.11264660953806088
      0.19827325479131078
      0.3258630800792618
      0.5079637793393771
      0.7594707505053202
      1.0982562033459682
      1.413760538990392
      ⋮
  96302.28863323135
  96651.90186197679
  96990.55801154737
  97320.4113426696
  97643.16714058812
  97960.19107601079
  98272.58192889007
  98677.64709780997
  99061.32455610296
  99428.0707768241
  99781.34728479401
 100000.0
u: 741-element Array{Array{Float64,1},1}:
 [1.0, 0.0, 0.0]
 [0.9999454641416529, 3.6167388700904066e-5, 1.837342657286889e-5]
 [0.9998682916702138, 3.6501568673507245e-5, 9.512324887291887e-5]
 [0.9995893049727836, 3.648256209271337e-5, 0.0003741090573328249]
 [0.9989372917174641, 3.642301308970641e-5, 0.0010258350325243646]
 [0.9976903793130836, 3.629296486648893e-5, 0.0022710916716201963]
 [0.9955926157131114, 3.6051509356670575e-5, 0.004363226970905501]
 [0.9923696413914693, 3.5654668525767474e-5, 0.007571648566731305]
 [0.9877553651695806, 3.506045397958778e-5, 0.0121545763223313]
 [0.981525309936306, 3.4236389650771523e-5, 0.01832587052354512]
 [0.9735276985633462, 3.316740549893925e-5, 0.02622526045095004]
 [0.9636787240920384, 2.88584465624168e-5, 0.03622277997903687]
 [0.9553388954692043, 2.8406119839430092e-5, 0.04462498803574076]
 ⋮
 [0.06955541585211228, 2.2420176462713666e-7, 1.2431796284739705]
 [0.06951090234959889, 2.2396150771774527e-7, 1.2437006412271576]
 [0.06946425323619385, 2.2371810707889965e-7, 1.2442043483265837]
 [0.06941598411807724, 2.2347256395264955e-7, 1.244693979657147]
 [0.06936648215085543, 2.2322559957496672e-7, 1.2451720913601354]
 [0.06931604223192987, 2.2297774175222173e-7, 1.245640729312093]
 [0.06892060326828084, 2.2091094162270443e-7, 1.2461047116394837]
 [0.06888920402272226, 2.2142850113651342e-7, 1.246694189400505]
 [0.06885308137307526, 2.2120992446613205e-7, 1.2472516924069228]
 [0.06881331868193945, 2.2098469431718675e-7, 1.2477837017922004]
 [0.06877081865232311, 2.2075496216571272e-7, 1.2482952539412668]
 [0.06848547763333795, 2.1907806147115115e-7, 1.2486135937114975]
```

**Comment by utkarsh530** [comment]
Fixed merge conflicts.

**Comment by ChrisRackauckas** [comment]
oh god, v1.5 tests go 💥

**Comment by ChrisRackauckas** [comment]
Switching Travis back to v1.4 for now.

**Pull request merged**
