### PR TITLE
Early terminate perform step when factorization fails

### PR DESCRIPTION
**Pull request by YingboMa**
Using the example in https://github.com/SciML/OrdinaryDiffEq.jl/issues/1710, we have
```julia
julia> DiffEqBase.default_factorize(A) = lu(A, check=false)

julia> sol = solve(prob, Rodas5()); # before
┌ Warning: Instability detected. Aborting
└ @ SciMLBase ~/.julia/packages/SciMLBase/YasGG/src/integrator_interface.jl:512

julia> sol = solve(prob, Rodas5()); # after

julia> sol.retcode
:Success
```

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
This'll need to happen to all Rosenbrocks. I assume Newton methods already have a safety catch for this?

**Comment by YingboMa** [comment]
Yeah, Newton is fine because of https://github.com/SciML/OrdinaryDiffEq.jl/blob/cd406fc03da416b6e2a8c1e296afbf072d93d74d/src/nlsolve/nlsolve.jl#L40

By in-place methods will error because `dolinsolve` doesn't handle this.

**Comment by YingboMa** [comment]
The test depends on https://github.com/SciML/DiffEqBase.jl/pull/799 . We need to rerun the CI after that's released.

**Comment by ChrisRackauckas** [comment]
Yes we can handle in-place in a following PR. That needs retcodes to be added to LinearSolve.jl.

**Pull request merged**
