### PR TITLE
Implemented KYKSSPRK32

### PR DESCRIPTION
**Pull request by ErikQQY**
Hello Chris, I implemented SSPRK32 method in Kubatko's paper, please review it. Then I would implement the other methods in next few days.

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Looks like there's a test error: https://github.com/SciML/OrdinaryDiffEq.jl/pull/1366/checks?check_run_id=2192281329#step:6:387

**Comment by ErikQQY** [comment]
Oops, I see the error. I will try it again.

**Comment by ChrisRackauckas** [comment]
I would suggest making sure it runs locally before pushing commits. Each of the test files can be run on their own so If you just run through it then most likely all of the tests will pass on CI. That might be a quicker feedback than waiting for CI.

**Comment by ErikQQY** [comment]
Ok, thank you, I am testing it locally.

**Comment by ChrisRackauckas** [comment]
This is named wrong, it should be the KYK one.

Also, isn't this https://github.com/SciML/OrdinaryDiffEq.jl/pull/669 ?

**Pull request closed without merging**
