### PR TITLE
Simplify ROCK methods for FastBroadcast.jl

### PR DESCRIPTION
**Pull request by ChrisRackauckas**

### CODE REVIEW

**Review by chriselrod — APPROVED** [review]
Should allow for compatibility with FastBroadcast 0.1.5, assuming there are no other places with redundant `@.. .=`.

**Comment by ChrisRackauckas** [comment]
Seems like FastBroadcast has issues with `copyto!` methods?

https://github.com/SciML/OrdinaryDiffEq.jl/pull/1403/checks?check_run_id=2567185508#step:6:363

**Comment by chriselrod** [comment]
It's the same problem that should be fixed with 0.1.6:
```julia
@.. _nlsolver.tmp .= uprev + α1[1] * k1[1] + α2[1] * k1[2]
```

**Comment by chriselrod** [comment]
Seems like that's all of them:
```sh
> git grep -nr '@\.\..*\.='                                                                                                                                                                                                                                                                           (base)
src/perform_step/pdirk_perform_step.jl:119:    @.. _nlsolver.tmp .= uprev + α1[1] * k1[1] + α2[1] * k1[2]
src/perform_step/rkc_perform_step.jl:300:    i < ccache.mdeg && (@.. uᵢ₋₂ .= uᵢ₋₁; uᵢ₋₁ .= u)
```

**Pull request merged**
