### PR TITLE
`_reshape` and `_vec` appropriately in more places

### PR DESCRIPTION
**Pull request by oscardssmith**
fixes https://github.com/SciML/OrdinaryDiffEq.jl/issues/2383 and related bugs.

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Needs tests

**Comment by oscardssmith** [comment]
will you let me merge this without tests for now? I have a testing overhaul that I want to get to soonish that will cover this (as well as lots of other things that are currently missing tests)

**Comment by ChrisRackauckas** [comment]
Looks like the FIRK tests failed.

**Comment by oscardssmith** [comment]
ah, this doesn't work for scalar. I think I'm found to merge the dolinsolve changes first and then update all the out of place methods to use dolinsolve which deals with this.

**Comment by ChrisRackauckas** [comment]
I guess. BDF just really needs to just use an array of arrays rather than this views of columns nonsense.

**Comment by prbzrg** [comment]
Are these changes released?

**Comment by ChrisRackauckas** [comment]
Oh god I can never keep track anymore. I think BDF, Radau, Core, and some others need it? @oscardssmith if you could do releases to match the changes that would help.

**Comment by oscardssmith** [comment]
will do.

**Comment by prbzrg** [comment]
@oscardssmith still not released 😟

**Comment by oscardssmith** [comment]
sorry for the delay (got distracted). https://github.com/JuliaRegistries/General/pull/114730 https://github.com/JuliaRegistries/General/pull/114731

**Pull request merged**
