### PR TITLE
fix memory leak on repeated `init(prob)`

### PR DESCRIPTION
**Pull request by oscardssmith**
this does not yet remove the leak.

edit: this does fix the memory leak if you get the order of your condition correct.

fixes https://github.com/SciML/OrdinaryDiffEq.jl/issues/2147

I'm not sure if this is easily testable.

### CODE REVIEW

**Comment by topolarity** [comment]
I don't think this is a proper fix - we should try to avoid this `gensym()` even when using progress

**Comment by ChrisRackauckas** [comment]
We can just remove the unique id names by default. You guys were the ones that wanted it 😅

**Comment by topolarity** [comment]
Yeah, I'm not sure why we wanted the unique identifier. @pepijndevos any problem if we just use a standard Symbol here?

**Comment by pepijndevos** [comment]
The reason is that every simulation in an ensemble needs an unique I'd to get its own progress bar.

**Comment by oscardssmith** [comment]
The problem is that making them symbols is that symbols are permalloced so they never get freed.

**Comment by pepijndevos** [comment]
Could we move the gensym up in the assembly problem?
Can IDs be strings instead?

**Comment by topolarity** [comment]
Do we really need the progress ID in the first place?

This is my first time looking at the progress setup, but it seems like if we reported the progress events as a delta, we wouldn't have to do `total_progress += new_progress[id] - old_progress[id]` (roughly speaking) and could just do `progress += delta`. Even better, wouldn't it be much more efficient to keep an atomic numerator and denominator, and have each simulation interact with those directly?

**Comment by pepijndevos** [comment]
Sure I mainly did this because it didn't require a sizable refactoring across SciML

**Pull request merged**
