### PR TITLE
Don't recompute Jacobian when it's fresh

### PR DESCRIPTION
**Pull request by YingboMa**
Fix https://github.com/SciML/OrdinaryDiffEq.jl/issues/1773

### CODE REVIEW

**Review by ChrisRackauckas — APPROVED** [review]

**Comment by ChrisRackauckas** [comment]
@YingboMa you're keeping on this one?

**Comment by gstein3m** [comment]
In order to save one more function evaluation when the Jacobian is fresh, we could call         
   calc_tderivative!(integrator, cache, dtd1, true)
instead of        
  calc_tderivative!(integrator, cache, dtd1, repeat_step)

**Comment by ChrisRackauckas** [comment]
yes, that's a good point. @YingboMa were you finishing this one?

**Comment by YingboMa** [comment]
Somehow I cannot reproduce the test failure.

**Comment by YingboMa** [comment]
Let's wait the new DelayDiffEq.jl's release and run the CI again.

**Comment by ChrisRackauckas** [comment]
> In order to save one more function evaluation when the Jacobian is fresh, we could call

I believe that is already done?
https://github.com/SciML/OrdinaryDiffEq.jl/blob/master/src/derivative_utils.jl#L807-L808

**Comment by YingboMa** [comment]
That's from this PR.

**Comment by ChrisRackauckas** [comment]
oh oops haha brain dead

**Pull request merged**
