### PR TITLE
Unroll error estimate & FSAL handling

### PR DESCRIPTION
**Pull request by YingboMa**

### CODE REVIEW

**Comment by YingboMa** [comment]
```julia
julia> function fff!(du,u,p,t)
        mul!(du, p, u)
       end
fff! (generic function with 1 method)

julia> prob = ODEProblem(fff!,rand(8),(0, 1.0), rand(8, 8));

julia> sol = @btime solve($prob, Vern9());
  11.799 μs (112 allocations: 20.09 KiB)

julia> tabalg = ExplicitRK(tableau = constructVernerEfficient9()); sol2 = @btime solve($prob,$tabalg);
  10.537 μs (83 allocations: 12.00 KiB)

julia> sol - sol2
VectorOfArray{Float64,2}:
6-element Vector{Vector{Float64}}:
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
 [0.0, -4.440892098500626e-16, 0.0, -4.440892098500626e-16, -2.220446049250313e-16, 0.0, -2.220446049250313e-16, 0.0]
 [0.0, -8.881784197001252e-16, 0.0, 0.0, -2.6645352591003757e-15, -1.7763568394002505e-15, -1.7763568394002505e-15, -8.881784197001252e-16]
 [1.7763568394002505e-15, 0.0, -7.105427357601002e-15, 0.0, -7.105427357601002e-15, 0.0, -1.7763568394002505e-15, -3.552713678800501e-15]
 [0.0, -3.552713678800501e-15, -1.0658141036401503e-14, -3.552713678800501e-15, -7.105427357601002e-15, -3.552713678800501e-15, -3.552713678800501e-15, -7.105427357601002e-15]
```

**Comment by YingboMa** [comment]
```julia
julia> sol = @btime solve($prob, Tsit5());
  9.564 μs (128 allocations: 16.41 KiB)

julia> tabalg = ExplicitRK(tableau = constructTsitouras5()); sol2 = @btime solve($prob,$tabalg);
  8.809 μs (88 allocations: 10.34 KiB)

julia> sol - sol2
VectorOfArray{Float64,2}:
10-element Vector{Vector{Float64}}:
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
 [-2.220446049250313e-16, 4.440892098500626e-16, 0.0, -4.440892098500626e-16, 0.0, 4.440892098500626e-16, -2.220446049250313e-16, 0.0]
 [0.0, 1.3322676295501878e-15, 0.0, -8.881784197001252e-16, 8.881784197001252e-16, 8.881784197001252e-16, 1.3322676295501878e-15, -4.440892098500626e-16]
 [1.7763568394002505e-15, 3.552713678800501e-15, 0.0, 8.881784197001252e-16, 2.6645352591003757e-15, 8.881784197001252e-16, 1.7763568394002505e-15, 0.0]
 [-3.552713678800501e-15, 3.552713678800501e-15, 1.7763568394002505e-15, 5.329070518200751e-15, 1.7763568394002505e-15, -1.7763568394002505e-15, 7.105427357601002e-15, 3.552713678800501e-15]
 [3.552713678800501e-15, 3.552713678800501e-15, 1.4210854715202004e-14, 1.4210854715202004e-14, 1.0658141036401503e-14, -1.0658141036401503e-14, 2.1316282072803006e-14, 0.0]
 [1.0658141036401503e-14, 1.4210854715202004e-14, 1.4210854715202004e-14, 2.1316282072803006e-14, 1.4210854715202004e-14, -1.0658141036401503e-14, 2.4868995751603507e-14, 0.0]
```

**Comment by YingboMa** [comment]
@ChrisRackauckas the DDE failure seems unrelated.

**Comment by ChrisRackauckas** [comment]
Yes, the dde tests are, can you bump the tolerances downstream?

But also, the regression tests are failing.

**Comment by YingboMa** [comment]
I think I fixed it in [99adf27](https://github.com/SciML/OrdinaryDiffEq.jl/pull/1852/commits/99adf271368d2181a9b1ed02e2f41dde1f620df2). Do you still see it?

**Comment by YingboMa** [comment]
Ah, there are regression tests in ordinarydiffeq-dot-jl as well.

**Review by ChrisRackauckas — APPROVED** [review]

**Pull request merged**
