### PR TITLE
add OrdinaryDiffEqLinearExponentialAlgorithm abstract type

### LINKED ISSUE #1247: Cannot use callbacks with linear exponential algorithms
MWE: 

```
using LinearAlgebra, Test
using OrdinaryDiffEq

function main()
  A0 = Matrix{Float64}(I(2))
  function update_func(A, u, _, t)
  end

  A = DiffEqArrayOperator(A0, update_func=update_func)

  condition(u,t,integrator) = t - 1.0
  affect!(integrator) = println(integrator.t)
  cb = ContinuousCallback(condition, affect!)

  prob = ODEProblem(A, [1.0, 0.0], (0.0, 2.0))
  solve(prob, MagnusGL4(), dt=1e-2, callback=cb)
end

main()
```

Error:

```
ERROR: LoadError: type MagnusGL4Cache has no field dz
Stacktrace:
 [1] getproperty(::OrdinaryDiffEq.MagnusGL4Cache{Array{Float64,1},Array{Float64,1},Array{Float64,2}}, ::Symbol) at ./Base.jl:33
 [2] get_tmp_cache at /Users/Joseph/Documents/code/libraries/julia/diffeq/dev/OrdinaryDiffEq/src/integrators/integrator_interface.jl:88 [inlined]
 [3] get_tmp_cache at /Users/Joseph/Documents/code/libraries/julia/diffeq/dev/OrdinaryDiffEq/src/integrators/integrator_interface.jl:74 [inlined]
 [4] get_tmp(::OrdinaryDiffEq.ODEIntegrator{MagnusGL4,true,Array{Float64,1},Nothing,Float64,DiffEqBase.NullParameters,Float64,Float64,Float64,Array{Array{Float64,1},1},ODESolution{Float64,2,Array{Array{Float64,1},1},Nothing,Nothing,Array{Float64,1},Array{Array{Array{Float64,1},1},1},ODEProblem{Array{Float64,1},Tuple{Float64,Float64},true,DiffEqBase.NullParameters,ODEFunction{true,DiffEqArrayOperator{Float64,Array{Float64,2},var"#update_func#1"},UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}},DiffEqBase.StandardODEProblem},MagnusGL4,OrdinaryDiffEq.InterpolationData{ODEFunction{true,DiffEqArrayOperator{Float64,Array{Float64,2},var"#update_func#1"},UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Array{Array{Float64,1},1},Array{Float64,1},Array{Array{Array{Float64,1},1},1},OrdinaryDiffEq.MagnusGL4Cache{Array{Float64,1},Array{Float64,1},Array{Float64,2}}},DiffEqBase.DEStats},ODEFunction{true,DiffEqArrayOperator{Float64,Array{Float64,2},var"#update_func#1"},UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},OrdinaryDiffEq.MagnusGL4Cache{Array{Float64,1},Array{Float64,1},Array{Float64,2}},OrdinaryDiffEq.DEOptions{Float64,Float64,Float64,Float64,typeof(DiffEqBase.ODE_DEFAULT_NORM),typeof(opnorm),CallbackSet{Tuple{ContinuousCallback{var"#condition#2",var"#affect!#3",var"#affect!#3",typeof(DiffEqBase.INITIALIZE_DEFAULT),Float64,Int64,Nothing,Int64}},Tuple{}},typeof(DiffEqBase.ODE_DEFAULT_ISOUTOFDOMAIN),typeof(DiffEqBase.ODE_DEFAULT_PROG_MESSAGE),typeof(DiffEqBase.ODE_DEFAULT_UNSTABLE_CHECK),DataStructures.BinaryHeap{Float64,DataStructures.LessThan},DataStructures.BinaryHeap{Float64,DataStructures.LessThan},Nothing,Nothing,Int64,Tuple{},Tuple{},Tuple{}},Array{Float64,1},Float64,Nothing,OrdinaryDiffEq.DefaultInit}, ::ContinuousCallback{var"#condition#2",var"#affect!#3",var"#affect!#3",typeof(DiffEqBase.INITIALIZE_DEFAULT),Float64,Int64,Nothing,Int64}) at /Users/Joseph/Documents/code/libraries/julia/diffeq/dev/DiffEqBase/src/callbacks.jl:344
 [5] get_condition(::OrdinaryDiffEq.ODEIntegrator{MagnusGL4,true,Array{Float64,1},Nothing,Float64,DiffEqBase.NullParameters,Float64,Float64,Float64,Array{Array{Float64,1},1},ODESolution{Float64,2,Array{Array{Float64,1},1},Nothing,Nothing,Array{Float64,1},Array{Array{Array{Float64,1},1},1},ODEProblem{Array{Float64,1},Tuple{Float64,Float64},true,DiffEqBase.NullParameters,ODEFunction{true,DiffEqArrayOperator{Float64,Array{Float64,2},var"#update_func#1"},UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}},DiffEqBase.StandardODEProblem},MagnusGL4,OrdinaryDiffEq.InterpolationData{ODEFunction{true,DiffEqArrayOperator{Float64,Array{Float64,2},var"#update_func#1"},UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Array{Array{Float64,1},1},Array{Float64,1},Array{Array{Array{Float64,1},1},1},OrdinaryDiffEq.MagnusGL4Cache{Array{Float64,1},Array{Float64,1},Array{Float64,2}}},DiffEqBase.DEStats},ODEFunction{true,DiffEqArrayOperator{Float64,Array{Float64,2},var"#update_func#1"},UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},OrdinaryDiffEq.MagnusGL4Cache{Array{Float64,1},Array{Float64,1},Array{Float64,2}},OrdinaryDiffEq.DEOptions{Float64,Float64,Float64,Float64,typeof(DiffEqBase.ODE_DEFAULT_NORM),typeof(opnorm),CallbackSet{Tuple{ContinuousCallback{var"#condition#2",var"#affect!#3",var"#affect!#3",typeof(DiffEqBase.INITIALIZE_DEFAULT),Float64,Int64,Nothing,Int64}},Tuple{}},typeof(DiffEqBase.ODE_DEFAULT_ISOUTOFDOMAIN),typeof(DiffEqBase.ODE_DEFAULT_PROG_MESSAGE),typeof(DiffEqBase.ODE_DEFAULT_UNSTABLE_CHECK),DataStructures.BinaryHeap{Float64,DataStructures.LessThan},DataStructures.BinaryHeap{Float64,DataStructures.LessThan},Nothing,Nothing,Int64,Tuple{},Tuple{},Tuple{}},Array{Float64,1},Float64,Nothing,OrdinaryDiffEq.DefaultInit}, ::ContinuousCallback{var"#condition#2",var"#affect!#3",var"#affect!#3",typeof(DiffEqBase.INITIALIZE_DEFAULT),Float64,Int64,Nothing,Int64}, ::Float64) at /Users/Joseph/Documents/code/libraries/julia/diffeq/dev/DiffEqBase/src/callbacks.jl:358
 [6] determine_event_occurance at /Users/Joseph/Documents/code/libraries/julia/diffeq/dev/DiffEqBase/src/callbacks.jl:553 [inlined]
 [7] find_callback_time(::OrdinaryDiffEq.ODEIntegrator{MagnusGL4,true,Array{Float64,1},Nothing,Float64,DiffEqBase.NullParameters,Float64,Float64,Float64,Array{Array{Float64,1},1},ODESolution{Float64,2,Array{Array{Float64,1},1},Nothing,Nothing,Array{Float64,1},Array{Array{Array{Float64,1},1},1},ODEProblem{Array{Float64,1},Tuple{Float64,Float64},true,DiffEqBase.NullParameters,ODEFunction{true,DiffEqArrayOperator{Float64,Array{Float64,2},var"#update_func#1"},UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}},DiffEqBase.StandardODEProblem},MagnusGL4,OrdinaryDiffEq.InterpolationData{ODEFunction{true,DiffEqArrayOperator{Float64,Array{Float64,2},var"#update_func#1"},UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Array{Array{Float64,1},1},Array{Float64,1},Array{Array{Array{Float64,1},1},1},OrdinaryDiffEq.MagnusGL4Cache{Array{Float64,1},Array{Float64,1},Array{Float64,2}}},DiffEqBase.DEStats},ODEFunction{true,DiffEqArrayOperator{Float64,Array{Float64,2},var"#update_func#1"},UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},OrdinaryDiffEq.MagnusGL4Cache{Array{Float64,1},Array{Float64,1},Array{Float64,2}},OrdinaryDiffEq.DEOptions{Float64,Float64,Float64,Float64,typeof(DiffEqBase.ODE_DEFAULT_NORM),typeof(opnorm),CallbackSet{Tuple{ContinuousCallback{var"#condition#2",var"#affect!#3",var"#affect!#3",typeof(DiffEqBase.INITIALIZE_DEFAULT),Float64,Int64,Nothing,Int64}},Tuple{}},typeof(DiffEqBase.ODE_DEFAULT_ISOUTOFDOMAIN),typeof(DiffEqBase.ODE_DEFAULT_PROG_MESSAGE),typeof(DiffEqBase.ODE_DEFAULT_UNSTABLE_CHECK),DataStructures.BinaryHeap{Float64,DataStructures.LessThan},DataStructures.BinaryHeap{Float64,DataStructures.LessThan},Nothing,Nothing,Int64,Tuple{},Tuple{},Tuple{}},Array{Float64,1},Float64,Nothing,OrdinaryDiffEq.DefaultInit}, ::ContinuousCallback{var"#condition#2",var"#affect!#3",var"#affect!#3",typeof(DiffEqBase.INITIALIZE_DEFAULT),Float64,Int64,Nothing,Int64}, ::Int64) at /Users/Joseph/Documents/code/libraries/julia/diffeq/dev/DiffEqBase/src/callbacks.jl:628
 [8] find_first_continuous_callback(::OrdinaryDiffEq.ODEIntegrator{MagnusGL4,true,Array{Float64,1},Nothing,Float64,DiffEqBase.NullParameters,Float64,Float64,Float64,Array{Array{Float64,1},1},ODESolution{Float64,2,Array{Array{Float64,1},1},Nothing,Nothing,Array{Float64,1},Array{Array{Array{Float64,1},1},1},ODEProblem{Array{Float64,1},Tuple{Float64,Float64},true,DiffEqBase.NullParameters,ODEFunction{true,DiffEqArrayOperator{Float64,Array{Float64,2},var"#update_func#1"},UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}},DiffEqBase.StandardODEProblem},MagnusGL4,OrdinaryDiffEq.InterpolationData{ODEFunction{true,DiffEqArrayOperator{Float64,Array{Float64,2},var"#update_func#1"},UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Array{Array{Float64,1},1},Array{Float64,1},Array{Array{Array{Float64,1},1},1},OrdinaryDiffEq.MagnusGL4Cache{Array{Float64,1},Array{Float64,1},Array{Float64,2}}},DiffEqBase.DEStats},ODEFunction{true,DiffEqArrayOperator{Float64,Array{Float64,2},var"#update_func#1"},UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},OrdinaryDiffEq.MagnusGL4Cache{Array{Float64,1},Array{Float64,1},Array{Float64,2}},OrdinaryDiffEq.DEOptions{Float64,Float64,Float64,Float64,typeof(DiffEqBase.ODE_DEFAULT_NORM),typeof(opnorm),CallbackSet{Tuple{ContinuousCallback{var"#condition#2",var"#affect!#3",var"#affect!#3",typeof(DiffEqBase.INITIALIZE_DEFAULT),Float64,Int64,Nothing,Int64}},Tuple{}},typeof(DiffEqBase.ODE_DEFAULT_ISOUTOFDOMAIN),typeof(DiffEqBase.ODE_DEFAULT_PROG_MESSAGE),typeof(DiffEqBase.ODE_DEFAULT_UNSTABLE_CHECK),DataStructures.BinaryHeap{Float64,DataStructures.LessThan},DataStructures.BinaryHeap{Float64,DataStructures.LessThan},Nothing,Nothing,Int64,Tuple{},Tuple{},Tuple{}},Array{Float64,1},Float64,Nothing,OrdinaryDiffEq.DefaultInit}, ::ContinuousCallback{var"#condition#2",var"#affect!#3",var"#affect!#3",typeof(DiffEqBase.INITIALIZE_DEFAULT),Float64,Int64,Nothing,Int64}) at /Users/Joseph/Documents/code/libraries/julia/diffeq/dev/DiffEqBase/src/callbacks.jl:398
 [9] handle_callbacks!(::OrdinaryDiffEq.ODEIntegrator{MagnusGL4,true,Array{Float64,1},Nothing,Float64,DiffEqBase.NullParameters,Float64,Float64,Float64,Array{Array{Float64,1},1},ODESolution{Float64,2,Array{Array{Float64,1},1},Nothing,Nothing,Array{Float64,1},Array{Array{Array{Float64,1},1},1},ODEProblem{Array{Float64,1},Tuple{Float64,Float64},true,DiffEqBase.NullParameters,ODEFunction{true,DiffEqArrayOperator{Float64,Array{Float64,2},var"#update_func#1"},UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}},DiffEqBase.StandardODEProblem},MagnusGL4,OrdinaryDiffEq.InterpolationData{ODEFunction{true,DiffEqArrayOperator{Float64,Array{Float64,2},var"#update_func#1"},UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Array{Array{Float64,1},1},Array{Float64,1},Array{Array{Array{Float64,1},1},1},OrdinaryDiffEq.MagnusGL4Cache{Array{Float64,1},Array{Float64,1},Array{Float64,2}}},DiffEqBase.DEStats},ODEFunction{true,DiffEqArrayOperator{Float64,Array{Float64,2},var"#update_func#1"},UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},OrdinaryDiffEq.MagnusGL4Cache{Array{Float64,1},Array{Float64,1},Array{Float64,2}},OrdinaryDiffEq.DEOptions{Float64,Float64,Float64,Float64,typeof(DiffEqBase.ODE_DEFAULT_NORM),typeof(opnorm),CallbackSet{Tuple{ContinuousCallback{var"#condition#2",var"#affect!#3",var"#affect!#3",typeof(DiffEqBase.INITIALIZE_DEFAULT),Float64,Int64,Nothing,Int64}},Tuple{}},typeof(DiffEqBase.ODE_DEFAULT_ISOUTOFDOMAIN),typeof(DiffEqBase.ODE_DEFAULT_PROG_MESSAGE),typeof(DiffEqBase.ODE_DEFAULT_UNSTABLE_CHECK),DataStructures.BinaryHeap{Float64,DataStructures.LessThan},DataStructures.BinaryHeap{Float64,DataStructures.LessThan},Nothing,Nothing,Int64,Tuple{},Tuple{},Tuple{}},Array{Float64,1},Float64,Nothing,OrdinaryDiffEq.DefaultInit}) at /Users/Joseph/Documents/code/libraries/julia/diffeq/dev/OrdinaryDiffEq/src/integrators/integrator_utils.jl:247
 [10] _loopfooter!(::OrdinaryDiffEq.ODEIntegrator{MagnusGL4,true,Array{Float64,1},Nothing,Float64,DiffEqBase.NullParameters,Float64,Float64,Float64,Array{Array{Float64,1},1},ODESolution{Float64,2,Array{Array{Float64,1},1},Nothing,Nothing,Array{Float64,1},Array{Array{Array{Float64,1},1},1},ODEProblem{Array{Float64,1},Tuple{Float64,Float64},true,DiffEqBase.NullParameters,ODEFunction{true,DiffEqArrayOperator{Float64,Array{Float64,2},var"#update_func#1"},UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}},DiffEqBase.StandardODEProblem},MagnusGL4,OrdinaryDiffEq.InterpolationData{ODEFunction{true,DiffEqArrayOperator{Float64,Array{Float64,2},var"#update_func#1"},UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Array{Array{Float64,1},1},Array{Float64,1},Array{Array{Array{Float64,1},1},1},OrdinaryDiffEq.MagnusGL4Cache{Array{Float64,1},Array{Float64,1},Array{Float64,2}}},DiffEqBase.DEStats},ODEFunction{true,DiffEqArrayOperator{Float64,Array{Float64,2},var"#update_func#1"},UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},OrdinaryDiffEq.MagnusGL4Cache{Array{Float64,1},Array{Float64,1},Array{Float64,2}},OrdinaryDiffEq.DEOptions{Float64,Float64,Float64,Float64,typeof(DiffEqBase.ODE_DEFAULT_NORM),typeof(opnorm),CallbackSet{Tuple{ContinuousCallback{var"#condition#2",var"#affect!#3",var"#affect!#3",typeof(DiffEqBase.INITIALIZE_DEFAULT),Float64,Int64,Nothing,Int64}},Tuple{}},typeof(DiffEqBase.ODE_DEFAULT_ISOUTOFDOMAIN),typeof(DiffEqBase.ODE_DEFAULT_PROG_MESSAGE),typeof(DiffEqBase.ODE_DEFAULT_UNSTABLE_CHECK),DataStructures.BinaryHeap{Float64,DataStructures.LessThan},DataStructures.BinaryHeap{Float64,DataStructures.LessThan},Nothing,Nothing,Int64,Tuple{},Tuple{},Tuple{}},Array{Float64,1},Float64,Nothing,OrdinaryDiffEq.DefaultInit}) at /Users/Joseph/Documents/code/libraries/julia/diffeq/dev/OrdinaryDiffEq/src/integrators/integrator_utils.jl:220
 [11] loopfooter! at /Users/Joseph/Documents/code/libraries/julia/diffeq/dev/OrdinaryDiffEq/src/integrators/integrator_utils.jl:166 [inlined]
 [12] solve!(::OrdinaryDiffEq.ODEIntegrator{MagnusGL4,true,Array{Float64,1},Nothing,Float64,DiffEqBase.NullParameters,Float64,Float64,Float64,Array{Array{Float64,1},1},ODESolution{Float64,2,Array{Array{Float64,1},1},Nothing,Nothing,Array{Float64,1},Array{Array{Array{Float64,1},1},1},ODEProblem{Array{Float64,1},Tuple{Float64,Float64},true,DiffEqBase.NullParameters,ODEFunction{true,DiffEqArrayOperator{Float64,Array{Float64,2},var"#update_func#1"},UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}},DiffEqBase.StandardODEProblem},MagnusGL4,OrdinaryDiffEq.InterpolationData{ODEFunction{true,DiffEqArrayOperator{Float64,Array{Float64,2},var"#update_func#1"},UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Array{Array{Float64,1},1},Array{Float64,1},Array{Array{Array{Float64,1},1},1},OrdinaryDiffEq.MagnusGL4Cache{Array{Float64,1},Array{Float64,1},Array{Float64,2}}},DiffEqBase.DEStats},ODEFunction{true,DiffEqArrayOperator{Float64,Array{Float64,2},var"#update_func#1"},UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},OrdinaryDiffEq.MagnusGL4Cache{Array{Float64,1},Array{Float64,1},Array{Float64,2}},OrdinaryDiffEq.DEOptions{Float64,Float64,Float64,Float64,typeof(DiffEqBase.ODE_DEFAULT_NORM),typeof(opnorm),CallbackSet{Tuple{ContinuousCallback{var"#condition#2",var"#affect!#3",var"#affect!#3",typeof(DiffEqBase.INITIALIZE_DEFAULT),Float64,Int64,Nothing,Int64}},Tuple{}},typeof(DiffEqBase.ODE_DEFAULT_ISOUTOFDOMAIN),typeof(DiffEqBase.ODE_DEFAULT_PROG_MESSAGE),typeof(DiffEqBase.ODE_DEFAULT_UNSTABLE_CHECK),DataStructures.BinaryHeap{Float64,DataStructures.LessThan},DataStructures.BinaryHeap{Float64,DataStructures.LessThan},Nothing,Nothing,Int64,Tuple{},Tuple{},Tuple{}},Array{Float64,1},Float64,Nothing,OrdinaryDiffEq.DefaultInit}) at /Users/Joseph/Documents/code/libraries/julia/diffeq/dev/OrdinaryDiffEq/src/solve.jl:429
 [13] #__solve#391 at /Users/Joseph/Documents/code/libraries/julia/diffeq/dev/OrdinaryDiffEq/src/solve.jl:5 [inlined]
 [14] solve_call(::ODEProblem{Array{Float64,1},Tuple{Float64,Float64},true,DiffEqBase.NullParameters,ODEFunction{true,DiffEqArrayOperator{Float64,Array{Float64,2},var"#update_func#1"},UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}},DiffEqBase.StandardODEProblem}, ::MagnusGL4; merge_callbacks::Bool, kwargs::Base.Iterators.Pairs{Symbol,Any,Tuple{Symbol,Symbol},NamedTuple{(:dt, :callback),Tuple{Float64,ContinuousCallback{var"#condition#2",var"#affect!#3",var"#affect!#3",typeof(DiffEqBase.INITIALIZE_DEFAULT),Float64,Int64,Nothing,Int64}}}}) at /Users/Joseph/Documents/code/libraries/julia/diffeq/dev/DiffEqBase/src/solve.jl:92
 [15] #solve_up#461 at /Users/Joseph/Documents/code/libraries/julia/diffeq/dev/DiffEqBase/src/solve.jl:114 [inlined]
 [16] #solve#460 at /Users/Joseph/Documents/code/libraries/julia/diffeq/dev/DiffEqBase/src/solve.jl:102 [inlined]
 [17] main() at /Users/Joseph/Documents/code/libraries/julia/diffeq/test.jl:16
 [18] top-level scope at /Users/Joseph/Documents/code/libraries/julia/diffeq/test.jl:19
 [19] include(::Function, ::Module, ::String) at ./Base.jl:380
 [20] include(::Module, ::String) at ./Base.jl:368
 [21] exec_options(::Base.JLOptions) at ./client.jl:296
 [22] _start() at ./client.jl:506
in expression starting at /Users/Joseph/Documents/code/libraries/julia/diffeq/test.jl:19
```

This appears to be because of this definition

```
@inline DiffEqBase.get_tmp_cache(integrator,alg::OrdinaryDiffEqExponentialAlgorithm,cache) = (cache.tmp,cache.dz)
```

in `integrators/integrator_interface.jl` which fails because the linear exponential algorithm caches don't define `dz`.

### PR DESCRIPTION
**Pull request by kleinhenz**
* this allows get_tmp_cache to be properly specialized
* closes #1247

I'm not sure if this is the right approach but this seems to fix my problem.

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
that looks good, thanks! Can you add the method to https://github.com/SciML/OrdinaryDiffEq.jl/blob/master/test/integrators/ode_cache_tests.jl#L11 so it gets exercised in an event handling test?

**Comment by ChrisRackauckas** [comment]
Oh wait, it needs a little bit more than that since it's not written for the linear methods. Could you convert your MWE into a test case?

**Comment by kanav99** [comment]
I think this would be covered because of this test - https://github.com/SciML/OrdinaryDiffEq.jl/blob/master/test/integrators/ode_cache_tests.jl#L67

**Comment by kanav99** [comment]
I am sorry I closed it by mistake

**Pull request merged**
