### PR TITLE
make CallbackCache real

### LINKED ISSUE #1222: VectorContinuousCallback doesn't work for complex valued solution
Using `VectorContinuousCallback` fails if the solution is complex valued because `CallbackCache` takes its type from the solution type but the root finding routines only work for real valued functions.

The issue is fixed by this patch, but I'm not sure if this is the right place to fix it.

```
diff --git a/src/solve.jl b/src/solve.jl
index ab6ef1e9..ffc2b3f9 100644
--- a/src/solve.jl
+++ b/src/solve.jl
@@ -193,10 +193,11 @@ function DiffEqBase.__init(prob::Union{DiffEqBase.AbstractODEProblem,DiffEqBase.
 
   max_len_cb = DiffEqBase.max_vector_callback_length(callbacks_internal)
   if max_len_cb isa VectorContinuousCallback
+    uBottomEltypeReal = real(uBottomEltype)
     if isinplace(prob)
-      callback_cache = DiffEqBase.CallbackCache(u,max_len_cb.len,uBottomEltype,uBottomEltype)
+      callback_cache = DiffEqBase.CallbackCache(u,max_len_cb.len,uBottomEltypeReal,uBottomEltypeReal)
     else
-      callback_cache = DiffEqBase.CallbackCache(max_len_cb.len,uBottomEltype,uBottomEltype)
+      callback_cache = DiffEqBase.CallbackCache(max_len_cb.len,uBottomEltypeReal,uBottomEltypeReal)
     end
   else
     callback_cache = nothing
```

MWE:
```
using LinearAlgebra, Printf
using DifferentialEquations

function main()
  function condition(out, u, t, integrator)
    out[1] = t - 0.5
  end

  function affect!(integrator, event_index)
    t = integrator.t
    @printf("t = %0.3f\n", t)
  end

  cb = VectorContinuousCallback(condition, affect!, 1)

  function f!(dψ, ψ, _, t)
    dψ .= -1.0im * ψ
  end

  ψ0 = complex([1.0])

  tmax = 2π
  tspan = (0.0, tmax)
  prob = ODEProblem(f!, ψ0, tspan)

  sol = solve(prob, dtmax=tmax/1000, callback=cb)
end

main()
```

error:

```
ERROR: LoadError: MethodError: no method matching isless(::Complex{Float64}, ::Int64)
Closest candidates are:
  isless(!Matched::Missing, ::Any) at missing.jl:87
  isless(!Matched::AbstractFloat, ::Real) at operators.jl:158
  isless(!Matched::ForwardDiff.Dual{Tx,V,N} where N where V, ::Integer) where Tx at /Users/Joseph/.julia/packages/ForwardDiff/sdToQ/src/dual.jl:139
  ...
Stacktrace:
 [1] <(::Complex{Float64}, ::Int64) at ./operators.jl:268
 [2] (::DiffEqBase.var"#411#412"{var"#affect!#4",var"#affect!#4",SubArray{Complex{Float64},1,Array{Complex{Float64},1},Tuple{UnitRange{Int64}},true},SubArray{Complex{Float64},1,Array{Complex{Float64},1},Tuple{UnitRange{Int64}},true}})(::Int64) at /Users/Joseph/.julia/packages/DiffEqBase/c1hSM/src/callbacks.jl:624
 [3] (::Base.var"#85#86"{DiffEqBase.var"#411#412"{var"#affect!#4",var"#affect!#4",SubArray{Complex{Float64},1,Array{Complex{Float64},1},Tuple{UnitRange{Int64}},true},SubArray{Complex{Float64},1,Array{Complex{Float64},1},Tuple{UnitRange{Int64}},true}}})(::Pair{Int64,Int64}) at ./none:0
 [4] iterate at ./iterators.jl:430 [inlined]
 [5] iterate at ./generator.jl:44 [inlined]
 [6] grow_to! at ./array.jl:726 [inlined]
 [7] collect at ./array.jl:663 [inlined]
 [8] findall at ./array.jl:2024 [inlined]
 [9] findall_events at /Users/Joseph/.julia/packages/DiffEqBase/c1hSM/src/callbacks.jl:624 [inlined]
 [10] determine_event_occurance at /Users/Joseph/.julia/packages/DiffEqBase/c1hSM/src/callbacks.jl:479 [inlined]
 [11] find_callback_time(::OrdinaryDiffEq.ODEIntegrator{CompositeAlgorithm{Tuple{Vern9,Rodas5{0,false,DefaultLinSolve,DataType}},AutoSwitch{Vern9,Rodas5{0,false,DefaultLinSolve,DataType},Rational{Int64},Int64}},true,Array{Complex{Float64},1},Nothing,Float64,DiffEqBase.NullParameters,Float64,Float64,Float64,Array{Array{Complex{Float64},1},1},OrdinaryDiffEq.ODECompositeSolution{Complex{Float64},2,Array{Array{Complex{Float64},1},1},Nothing,Nothing,Array{Float64,1},Array{Array{Array{Complex{Float64},1},1},1},ODEProblem{Array{Complex{Float64},1},Tuple{Float64,Float64},true,DiffEqBase.NullParameters,ODEFunction{true,var"#f!#5",UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}},DiffEqBase.StandardODEProblem},CompositeAlgorithm{Tuple{Vern9,Rodas5{0,false,DefaultLinSolve,DataType}},AutoSwitch{Vern9,Rodas5{0,false,DefaultLinSolve,DataType},Rational{Int64},Int64}},OrdinaryDiffEq.CompositeInterpolationData{ODEFunction{true,var"#f!#5",UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Array{Array{Complex{Float64},1},1},Array{Float64,1},Array{Array{Array{Complex{Float64},1},1},1},OrdinaryDiffEq.CompositeCache{Tuple{OrdinaryDiffEq.Vern9Cache{Array{Complex{Float64},1},Array{Complex{Float64},1},Array{Complex{Float64},1},OrdinaryDiffEq.Vern9Tableau{Complex{Float64},Float64}},OrdinaryDiffEq.Rosenbrock5Cache{Array{Complex{Float64},1},Array{Complex{Float64},1},Array{Complex{Float64},1},Array{Complex{Float64},2},Array{Complex{Float64},2},OrdinaryDiffEq.Rodas5Tableau{Complex{Float64},Float64},DiffEqBase.TimeGradientWrapper{ODEFunction{true,var"#f!#5",UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Array{Complex{Float64},1},DiffEqBase.NullParameters},DiffEqBase.UJacobianWrapper{ODEFunction{true,var"#f!#5",UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Float64,DiffEqBase.NullParameters},DefaultLinSolve,FiniteDiff.JacobianCache{Array{Complex{Float64},1},Array{Complex{Float64},1},Array{Complex{Float64},1},UnitRange{Int64},Nothing,Val{:forward},Complex{Float64}},FiniteDiff.GradientCache{Nothing,Array{Complex{Float64},1},Array{Complex{Float64},1},Float64,Val{:forward},Complex{Float64},Val{true}}}},AutoSwitch{Vern9,Rodas5{0,false,DefaultLinSolve,DataType},Rational{Int64},Int64}}},DiffEqBase.DEStats},ODEFunction{true,var"#f!#5",UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},OrdinaryDiffEq.CompositeCache{Tuple{OrdinaryDiffEq.Vern9Cache{Array{Complex{Float64},1},Array{Complex{Float64},1},Array{Complex{Float64},1},OrdinaryDiffEq.Vern9Tableau{Complex{Float64},Float64}},OrdinaryDiffEq.Rosenbrock5Cache{Array{Complex{Float64},1},Array{Complex{Float64},1},Array{Complex{Float64},1},Array{Complex{Float64},2},Array{Complex{Float64},2},OrdinaryDiffEq.Rodas5Tableau{Complex{Float64},Float64},DiffEqBase.TimeGradientWrapper{ODEFunction{true,var"#f!#5",UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Array{Complex{Float64},1},DiffEqBase.NullParameters},DiffEqBase.UJacobianWrapper{ODEFunction{true,var"#f!#5",UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Float64,DiffEqBase.NullParameters},DefaultLinSolve,FiniteDiff.JacobianCache{Array{Complex{Float64},1},Array{Complex{Float64},1},Array{Complex{Float64},1},UnitRange{Int64},Nothing,Val{:forward},Complex{Float64}},FiniteDiff.GradientCache{Nothing,Array{Complex{Float64},1},Array{Complex{Float64},1},Float64,Val{:forward},Complex{Float64},Val{true}}}},AutoSwitch{Vern9,Rodas5{0,false,DefaultLinSolve,DataType},Rational{Int64},Int64}},OrdinaryDiffEq.DEOptions{Float64,Float64,Float64,Float64,typeof(DiffEqBase.ODE_DEFAULT_NORM),typeof(opnorm),CallbackSet{Tuple{VectorContinuousCallback{var"#condition#3",var"#affect!#4",var"#affect!#4",typeof(DiffEqBase.INITIALIZE_DEFAULT),Float64,Int64,Nothing,Int64}},Tuple{}},typeof(DiffEqBase.ODE_DEFAULT_ISOUTOFDOMAIN),typeof(DiffEqBase.ODE_DEFAULT_PROG_MESSAGE),typeof(DiffEqBase.ODE_DEFAULT_UNSTABLE_CHECK),DataStructures.BinaryHeap{Float64,DataStructures.LessThan},DataStructures.BinaryHeap{Float64,DataStructures.LessThan},Nothing,Nothing,Int64,Tuple{},Tuple{},Tuple{}},Array{Complex{Float64},1},Complex{Float64},DiffEqBase.CallbackCache{Array{Complex{Float64},1},Array{Complex{Float64},1}},OrdinaryDiffEq.DefaultInit}, ::VectorContinuousCallback{var"#condition#3",var"#affect!#4",var"#affect!#4",typeof(DiffEqBase.INITIALIZE_DEFAULT),Float64,Int64,Nothing,Int64}, ::Int64) at /Users/Joseph/.julia/packages/DiffEqBase/c1hSM/src/callbacks.jl:690
 [12] find_first_continuous_callback at /Users/Joseph/.julia/packages/DiffEqBase/c1hSM/src/callbacks.jl:398 [inlined]
 [13] handle_callbacks! at /Users/Joseph/Documents/code/libraries/julia/diffeq/dev/OrdinaryDiffEq/src/integrators/integrator_utils.jl:247 [inlined]
 [14] _loopfooter!(::OrdinaryDiffEq.ODEIntegrator{CompositeAlgorithm{Tuple{Vern9,Rodas5{0,false,DefaultLinSolve,DataType}},AutoSwitch{Vern9,Rodas5{0,false,DefaultLinSolve,DataType},Rational{Int64},Int64}},true,Array{Complex{Float64},1},Nothing,Float64,DiffEqBase.NullParameters,Float64,Float64,Float64,Array{Array{Complex{Float64},1},1},OrdinaryDiffEq.ODECompositeSolution{Complex{Float64},2,Array{Array{Complex{Float64},1},1},Nothing,Nothing,Array{Float64,1},Array{Array{Array{Complex{Float64},1},1},1},ODEProblem{Array{Complex{Float64},1},Tuple{Float64,Float64},true,DiffEqBase.NullParameters,ODEFunction{true,var"#f!#5",UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}},DiffEqBase.StandardODEProblem},CompositeAlgorithm{Tuple{Vern9,Rodas5{0,false,DefaultLinSolve,DataType}},AutoSwitch{Vern9,Rodas5{0,false,DefaultLinSolve,DataType},Rational{Int64},Int64}},OrdinaryDiffEq.CompositeInterpolationData{ODEFunction{true,var"#f!#5",UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Array{Array{Complex{Float64},1},1},Array{Float64,1},Array{Array{Array{Complex{Float64},1},1},1},OrdinaryDiffEq.CompositeCache{Tuple{OrdinaryDiffEq.Vern9Cache{Array{Complex{Float64},1},Array{Complex{Float64},1},Array{Complex{Float64},1},OrdinaryDiffEq.Vern9Tableau{Complex{Float64},Float64}},OrdinaryDiffEq.Rosenbrock5Cache{Array{Complex{Float64},1},Array{Complex{Float64},1},Array{Complex{Float64},1},Array{Complex{Float64},2},Array{Complex{Float64},2},OrdinaryDiffEq.Rodas5Tableau{Complex{Float64},Float64},DiffEqBase.TimeGradientWrapper{ODEFunction{true,var"#f!#5",UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Array{Complex{Float64},1},DiffEqBase.NullParameters},DiffEqBase.UJacobianWrapper{ODEFunction{true,var"#f!#5",UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Float64,DiffEqBase.NullParameters},DefaultLinSolve,FiniteDiff.JacobianCache{Array{Complex{Float64},1},Array{Complex{Float64},1},Array{Complex{Float64},1},UnitRange{Int64},Nothing,Val{:forward},Complex{Float64}},FiniteDiff.GradientCache{Nothing,Array{Complex{Float64},1},Array{Complex{Float64},1},Float64,Val{:forward},Complex{Float64},Val{true}}}},AutoSwitch{Vern9,Rodas5{0,false,DefaultLinSolve,DataType},Rational{Int64},Int64}}},DiffEqBase.DEStats},ODEFunction{true,var"#f!#5",UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},OrdinaryDiffEq.CompositeCache{Tuple{OrdinaryDiffEq.Vern9Cache{Array{Complex{Float64},1},Array{Complex{Float64},1},Array{Complex{Float64},1},OrdinaryDiffEq.Vern9Tableau{Complex{Float64},Float64}},OrdinaryDiffEq.Rosenbrock5Cache{Array{Complex{Float64},1},Array{Complex{Float64},1},Array{Complex{Float64},1},Array{Complex{Float64},2},Array{Complex{Float64},2},OrdinaryDiffEq.Rodas5Tableau{Complex{Float64},Float64},DiffEqBase.TimeGradientWrapper{ODEFunction{true,var"#f!#5",UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Array{Complex{Float64},1},DiffEqBase.NullParameters},DiffEqBase.UJacobianWrapper{ODEFunction{true,var"#f!#5",UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Float64,DiffEqBase.NullParameters},DefaultLinSolve,FiniteDiff.JacobianCache{Array{Complex{Float64},1},Array{Complex{Float64},1},Array{Complex{Float64},1},UnitRange{Int64},Nothing,Val{:forward},Complex{Float64}},FiniteDiff.GradientCache{Nothing,Array{Complex{Float64},1},Array{Complex{Float64},1},Float64,Val{:forward},Complex{Float64},Val{true}}}},AutoSwitch{Vern9,Rodas5{0,false,DefaultLinSolve,DataType},Rational{Int64},Int64}},OrdinaryDiffEq.DEOptions{Float64,Float64,Float64,Float64,typeof(DiffEqBase.ODE_DEFAULT_NORM),typeof(opnorm),CallbackSet{Tuple{VectorContinuousCallback{var"#condition#3",var"#affect!#4",var"#affect!#4",typeof(DiffEqBase.INITIALIZE_DEFAULT),Float64,Int64,Nothing,Int64}},Tuple{}},typeof(DiffEqBase.ODE_DEFAULT_ISOUTOFDOMAIN),typeof(DiffEqBase.ODE_DEFAULT_PROG_MESSAGE),typeof(DiffEqBase.ODE_DEFAULT_UNSTABLE_CHECK),DataStructures.BinaryHeap{Float64,DataStructures.LessThan},DataStructures.BinaryHeap{Float64,DataStructures.LessThan},Nothing,Nothing,Int64,Tuple{},Tuple{},Tuple{}},Array{Complex{Float64},1},Complex{Float64},DiffEqBase.CallbackCache{Array{Complex{Float64},1},Array{Complex{Float64},1}},OrdinaryDiffEq.DefaultInit}) at /Users/Joseph/Documents/code/libraries/julia/diffeq/dev/OrdinaryDiffEq/src/integrators/integrator_utils.jl:202
 [15] loopfooter! at /Users/Joseph/Documents/code/libraries/julia/diffeq/dev/OrdinaryDiffEq/src/integrators/integrator_utils.jl:166 [inlined]
 [16] solve!(::OrdinaryDiffEq.ODEIntegrator{CompositeAlgorithm{Tuple{Vern9,Rodas5{0,false,DefaultLinSolve,DataType}},AutoSwitch{Vern9,Rodas5{0,false,DefaultLinSolve,DataType},Rational{Int64},Int64}},true,Array{Complex{Float64},1},Nothing,Float64,DiffEqBase.NullParameters,Float64,Float64,Float64,Array{Array{Complex{Float64},1},1},OrdinaryDiffEq.ODECompositeSolution{Complex{Float64},2,Array{Array{Complex{Float64},1},1},Nothing,Nothing,Array{Float64,1},Array{Array{Array{Complex{Float64},1},1},1},ODEProblem{Array{Complex{Float64},1},Tuple{Float64,Float64},true,DiffEqBase.NullParameters,ODEFunction{true,var"#f!#5",UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}},DiffEqBase.StandardODEProblem},CompositeAlgorithm{Tuple{Vern9,Rodas5{0,false,DefaultLinSolve,DataType}},AutoSwitch{Vern9,Rodas5{0,false,DefaultLinSolve,DataType},Rational{Int64},Int64}},OrdinaryDiffEq.CompositeInterpolationData{ODEFunction{true,var"#f!#5",UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Array{Array{Complex{Float64},1},1},Array{Float64,1},Array{Array{Array{Complex{Float64},1},1},1},OrdinaryDiffEq.CompositeCache{Tuple{OrdinaryDiffEq.Vern9Cache{Array{Complex{Float64},1},Array{Complex{Float64},1},Array{Complex{Float64},1},OrdinaryDiffEq.Vern9Tableau{Complex{Float64},Float64}},OrdinaryDiffEq.Rosenbrock5Cache{Array{Complex{Float64},1},Array{Complex{Float64},1},Array{Complex{Float64},1},Array{Complex{Float64},2},Array{Complex{Float64},2},OrdinaryDiffEq.Rodas5Tableau{Complex{Float64},Float64},DiffEqBase.TimeGradientWrapper{ODEFunction{true,var"#f!#5",UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Array{Complex{Float64},1},DiffEqBase.NullParameters},DiffEqBase.UJacobianWrapper{ODEFunction{true,var"#f!#5",UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Float64,DiffEqBase.NullParameters},DefaultLinSolve,FiniteDiff.JacobianCache{Array{Complex{Float64},1},Array{Complex{Float64},1},Array{Complex{Float64},1},UnitRange{Int64},Nothing,Val{:forward},Complex{Float64}},FiniteDiff.GradientCache{Nothing,Array{Complex{Float64},1},Array{Complex{Float64},1},Float64,Val{:forward},Complex{Float64},Val{true}}}},AutoSwitch{Vern9,Rodas5{0,false,DefaultLinSolve,DataType},Rational{Int64},Int64}}},DiffEqBase.DEStats},ODEFunction{true,var"#f!#5",UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},OrdinaryDiffEq.CompositeCache{Tuple{OrdinaryDiffEq.Vern9Cache{Array{Complex{Float64},1},Array{Complex{Float64},1},Array{Complex{Float64},1},OrdinaryDiffEq.Vern9Tableau{Complex{Float64},Float64}},OrdinaryDiffEq.Rosenbrock5Cache{Array{Complex{Float64},1},Array{Complex{Float64},1},Array{Complex{Float64},1},Array{Complex{Float64},2},Array{Complex{Float64},2},OrdinaryDiffEq.Rodas5Tableau{Complex{Float64},Float64},DiffEqBase.TimeGradientWrapper{ODEFunction{true,var"#f!#5",UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Array{Complex{Float64},1},DiffEqBase.NullParameters},DiffEqBase.UJacobianWrapper{ODEFunction{true,var"#f!#5",UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Float64,DiffEqBase.NullParameters},DefaultLinSolve,FiniteDiff.JacobianCache{Array{Complex{Float64},1},Array{Complex{Float64},1},Array{Complex{Float64},1},UnitRange{Int64},Nothing,Val{:forward},Complex{Float64}},FiniteDiff.GradientCache{Nothing,Array{Complex{Float64},1},Array{Complex{Float64},1},Float64,Val{:forward},Complex{Float64},Val{true}}}},AutoSwitch{Vern9,Rodas5{0,false,DefaultLinSolve,DataType},Rational{Int64},Int64}},OrdinaryDiffEq.DEOptions{Float64,Float64,Float64,Float64,typeof(DiffEqBase.ODE_DEFAULT_NORM),typeof(opnorm),CallbackSet{Tuple{VectorContinuousCallback{var"#condition#3",var"#affect!#4",var"#affect!#4",typeof(DiffEqBase.INITIALIZE_DEFAULT),Float64,Int64,Nothing,Int64}},Tuple{}},typeof(DiffEqBase.ODE_DEFAULT_ISOUTOFDOMAIN),typeof(DiffEqBase.ODE_DEFAULT_PROG_MESSAGE),typeof(DiffEqBase.ODE_DEFAULT_UNSTABLE_CHECK),DataStructures.BinaryHeap{Float64,DataStructures.LessThan},DataStructures.BinaryHeap{Float64,DataStructures.LessThan},Nothing,Nothing,Int64,Tuple{},Tuple{},Tuple{}},Array{Complex{Float64},1},Complex{Float64},DiffEqBase.CallbackCache{Array{Complex{Float64},1},Array{Complex{Float64},1}},OrdinaryDiffEq.DefaultInit}) at /Users/Joseph/Documents/code/libraries/julia/diffeq/dev/OrdinaryDiffEq/src/solve.jl:426
 [17] __solve(::ODEProblem{Array{Complex{Float64},1},Tuple{Float64,Float64},true,DiffEqBase.NullParameters,ODEFunction{true,var"#f!#5",UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}},DiffEqBase.StandardODEProblem}, ::CompositeAlgorithm{Tuple{Vern9,Rodas5{0,false,DefaultLinSolve,DataType}},AutoSwitch{Vern9,Rodas5{0,false,DefaultLinSolve,DataType},Rational{Int64},Int64}}; kwargs::Base.Iterators.Pairs{Symbol,Any,NTuple{4,Symbol},NamedTuple{(:default_set, :second_time, :dtmax, :callback),Tuple{Bool,Bool,Float64,VectorContinuousCallback{var"#condition#3",var"#affect!#4",var"#affect!#4",typeof(DiffEqBase.INITIALIZE_DEFAULT),Float64,Int64,Nothing,Int64}}}}) at /Users/Joseph/Documents/code/libraries/julia/diffeq/dev/OrdinaryDiffEq/src/solve.jl:5
 [18] __solve(::ODEProblem{Array{Complex{Float64},1},Tuple{Float64,Float64},true,DiffEqBase.NullParameters,ODEFunction{true,var"#f!#5",UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}},DiffEqBase.StandardODEProblem}, ::Nothing; default_set::Bool, kwargs::Base.Iterators.Pairs{Symbol,Any,Tuple{Symbol,Symbol,Symbol},NamedTuple{(:second_time, :dtmax, :callback),Tuple{Bool,Float64,VectorContinuousCallback{var"#condition#3",var"#affect!#4",var"#affect!#4",typeof(DiffEqBase.INITIALIZE_DEFAULT),Float64,Int64,Nothing,Int64}}}}) at /Users/Joseph/.julia/packages/DifferentialEquations/fpohE/src/default_solve.jl:7
 [19] #__solve#471 at /Users/Joseph/.julia/packages/DiffEqBase/c1hSM/src/solve.jl:254 [inlined]
 [20] solve_call(::ODEProblem{Array{Complex{Float64},1},Tuple{Float64,Float64},true,DiffEqBase.NullParameters,ODEFunction{true,var"#f!#5",UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}},DiffEqBase.StandardODEProblem}; merge_callbacks::Bool, kwargs::Base.Iterators.Pairs{Symbol,Any,Tuple{Symbol,Symbol},NamedTuple{(:dtmax, :callback),Tuple{Float64,VectorContinuousCallback{var"#condition#3",var"#affect!#4",var"#affect!#4",typeof(DiffEqBase.INITIALIZE_DEFAULT),Float64,Int64,Nothing,Int64}}}}) at /Users/Joseph/.julia/packages/DiffEqBase/c1hSM/src/solve.jl:92
 [21] #solve_up#461 at /Users/Joseph/.julia/packages/DiffEqBase/c1hSM/src/solve.jl:117 [inlined]
 [22] #solve#460 at /Users/Joseph/.julia/packages/DiffEqBase/c1hSM/src/solve.jl:102 [inlined]
 [23] main() at /Users/Joseph/Documents/code/libraries/julia/diffeq/test.jl:26
 [24] top-level scope at /Users/Joseph/Documents/code/libraries/julia/diffeq/test.jl:29
 [25] include(::Module, ::String) at ./Base.jl:377
 [26] exec_options(::Base.JLOptions) at ./client.jl:288
 [27] _start() at ./client.jl:484
in expression starting at /Users/Joseph/Documents/code/libraries/julia/diffeq/test.jl:29
```

### PR DESCRIPTION
**Pull request by kleinhenz**
closes #1222. Make sure that element type for `CallbackCache` is real.

### CODE REVIEW

**Comment by devmotion** [comment]
Maybe add the MWE in the issue as a test?

**Comment by ChrisRackauckas** [comment]
yes that would be a good idea

**Comment by kleinhenz** [comment]
added a test

**Comment by ChrisRackauckas** [comment]
Thanks! Sorry for the slow responses during JuliaCon.

**Pull request merged**
