### PR TITLE
Migrate to JuliaGPU's CI setup

### PR DESCRIPTION
**Pull request by christopher-dG**
First try at this, might need some fixing up.

### CODE REVIEW

**Comment by christopher-dG** [comment]
Seems like the GPU job is timing out, a lot of time is spent downloading artifacts.

**Comment by ChrisRackauckas** [comment]
Are others having this?

**Comment by devmotion** [comment]
Maybe we should start caching artifacts as described in https://discourse.julialang.org/t/recommendation-cache-julia-artifacts-in-ci-services/35484?u=devmotion (might be useful on Travis as well)?

**Comment by christopher-dG** [comment]
Artifacts are being cached in GitLab, so as soon as one job succeeds it should be stored. I haven't tried any other repos but I'll do that now and see what happens.

**Comment by christopher-dG** [comment]
The `intel` runner seems to have a pretty flaky network connection.

**Comment by christopher-dG** [comment]
Out of memory after 2.5 hours! https://gitlab.com/JuliaGPU/OrdinaryDiffEq.jl/-/jobs/588230472

**Comment by ChrisRackauckas** [comment]
https://gitlab.com/JuliaGPU/OrdinaryDiffEq.jl/-/jobs/588230472#L6614

@maleadt is that statistic correct or is it underreporting how much memory we are using?

**Comment by ChrisRackauckas** [comment]
This repo might need a tag requesting the "not the worst" GPU resources: the GPU cost here isn't all that much (probably not more than 1GB?), but it's not just unit tests: it's running a (small) PDE integration test and that's what's failing.

**Comment by maleadt** [comment]
```
   LoadError: Out of GPU memory trying to allocate 768.000 KiB
  Effective GPU memory usage: 99.98% (31.714 GiB/31.719 GiB)
  CuArrays allocator usage: 8.516 MiB (capped at 512.000 MiB)
  BinnedPool usage: 8.516 MiB (8.516 MiB allocated, 0 bytes cached)
```

So this job was killed because the GPU was almost entirely used, but outside of CuArrays. You should pick a device that the most memory free, e.g., https://github.com/JuliaGPU/CUDA.jl/blob/08a83b5d9072555d469894b6443fced04c9593e9/test/runtests.jl#L106-L127'

Artifacts are being cached by Gitlab indeed, but that caching is fairly slow (it zips up the cache directory). We might have to find a better way, like hosting a caching Pkg server on the runners (which presumably is pretty easy).

**Comment by ChrisRackauckas** [comment]
>I seem to have lost my commit rights to this branch, so please apply this for me -- we should be activating the downstream env in local tests too.

Yeah sorry about that: I removed ownership since I thought we were done with all of the updates. I lost track of this one. I'll merge and we can do a followup PR if needed.

**Pull request merged**
