### PR TITLE
Define prepare_alg dispatch for OrdinaryDiffEq AD algorithms

### PR DESCRIPTION
**Pull request by ChrisRackauckas**
Requires https://github.com/SciML/DiffEqBase.jl/pull/698

### CODE REVIEW

**Comment by chriselrod** [comment]
This may be the primary cause of the inference regression in Pumas.

**Comment by ChrisRackauckas** [comment]
This PR causes the biggest decrease to compile times 😅

**Comment by chriselrod** [comment]
Well, commenting out `prepare_alg` reduced inference of the first `solve` on a single subject in Pumas from 16.8 down to 9.7 seconds.

**Comment by ChrisRackauckas** [comment]
But having this allows for the things to fully precompile, which is the full 22 to 3 seconds precompile 🌊

**Comment by chriselrod** [comment]
Yeah, I think a better fix is to just avoid the type instability in Pumas

**Pull request merged**
