### PR TITLE
Rodas4P2 included

### PR DESCRIPTION
**Pull request by gstein3m**

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Add a convergence test https://github.com/SciML/OrdinaryDiffEq.jl/blob/master/test/algconvergence/ode_rosenbrock_tests.jl

**Comment by ChrisRackauckas** [comment]
It looks like that tableau as written only gets first order convergence. You will want to play with it locally. Note that you can do `plot(sim)` to plot the convergence test. Most likely one of the values in the tableau were copied incorrectly.

**Comment by gstein3m** [comment]
Could the continuous output be the reason? Maybe I have to check these coefficients.

**Comment by ChrisRackauckas** [comment]
Thanks! 

Add it to the list? https://github.com/SciML/DiffEqDocs.jl/blob/master/docs/src/solvers/ode_solve.md

**Pull request merged**
