### PR TITLE
Remove unnecessary branches of Vern7, Vern9 and Tsit5

### PR DESCRIPTION
**Pull request by ErikQQY**
This PR continues the work in #1833, remove the unnecessary ```Array{Float64}``` branches for ```Vern7``` and ```Vern9```

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Tsit5 and DP5 might have one as well?

**Review by ChrisRackauckas — APPROVED** [review]

**Comment by ErikQQY** [comment]
DP5 doesn't have the```Array{Float64}``` branch
https://github.com/SciML/OrdinaryDiffEq.jl/blob/6f9a480c6156e641c6b697c195259e120a222730/src/perform_step/low_order_rk_perform_step.jl#L1017-L1020

https://github.com/SciML/OrdinaryDiffEq.jl/blob/6f9a480c6156e641c6b697c195259e120a222730/src/perform_step/low_order_rk_perform_step.jl#L960-L963

**Comment by ChrisRackauckas** [comment]
It would be good to document your changes in https://docs.sciml.ai/OrdinaryDiffEq/stable/nonstiff/explicitrk/

**Comment by ErikQQY** [comment]
Sure, I will send a PR to the docs.

**Pull request merged**
