### PR TITLE
New methods Rodas23W / Rodas3P with error test for interpolation, see issue 2054 https://github.com/SciML/OrdinaryDiffEq.jl/issues/2054

### PR DESCRIPTION
**Pull request by gstein3m**
## Checklist

- [ x] Appropriate tests were added: wp precision benchmarks were successful 
- [x ] Any code changes were done in a way that does not break public API
- [ ] All documentation related to code changes were updated
- [ x] The new code follows the
  [contributor guidelines](https://github.com/SciML/.github/blob/master/CONTRIBUTING.md), in particular the [SciML Style Guide](https://github.com/SciML/SciMLStyle) and
  [COLPRAC](https://github.com/SciML/COLPRAC).
- [ ] Any new documentation only uses public API

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Still needs tests?

**Comment by ChrisRackauckas** [comment]
Wow, that was fast. Christmas came early! Looks like this needs tests. @oscardssmith maybe you might want to setup a few benchmarks? I know you have cases you were looking at.

**Comment by gstein3m** [comment]
Enclosed are some first Benchs,

Merry Christmas

Gerd


Von: Christopher Rackauckas ***@***.***>
Gesendet: Montag, 25. Dezember 2023 03:00
An: SciML/OrdinaryDiffEq.jl ***@***.***>
Cc: Steinebach, Gerd ***@***.***>; Author ***@***.***>
Betreff: Re: [SciML/OrdinaryDiffEq.jl] New methods Rodas23W / Rodas3P with error test for interpolation, see issue 2054 https://github.com/SciML/OrdinaryDiffEq.jl/issues/2054 (PR #2092)


Wow, that was fast. Christmas came early! Looks like this needs tests. @oscardssmith<https://github.com/oscardssmith> maybe you might want to setup a few benchmarks? I know you have cases you were looking at.

**Comment by oscardssmith** [comment]
Is this ready to merge?

**Comment by gstein3m** [comment]
> Is this ready to merge?

From my point of view, yes.

**Comment by ChrisRackauckas** [comment]
Can you rebase onto latest master? I think that should fix up the tests on the Buildkite and everything should be green here.

**Pull request merged**
