### PR TITLE
feat: allow initialization of null integrators

### PR DESCRIPTION
**Pull request by AayushSabharwal**
Requires
- https://github.com/SciML/ModelingToolkit.jl/pull/2729
- https://github.com/SciML/OrdinaryDiffEq.jl/pull/2209
- https://github.com/SciML/DiffEqBase.jl/pull/1051
- https://github.com/SciML/SciMLBase.jl/pull/698

## Checklist

- [ ] Appropriate tests were added
- [ ] Any code changes were done in a way that does not break public API
- [ ] All documentation related to code changes were updated
- [ ] The new code follows the
  [contributor guidelines](https://github.com/SciML/.github/blob/master/CONTRIBUTING.md), in particular the [SciML Style Guide](https://github.com/SciML/SciMLStyle) and
  [COLPRAC](https://github.com/SciML/COLPRAC).
- [ ] Any new documentation only uses public API

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
What's a case that needs this?

**Comment by AayushSabharwal** [comment]
This was part of the rework that allows parameters to be unknowns in the initialization system. That bit is on hold for the time being, pending the discussion in https://github.com/SciML/ModelingToolkit.jl/issues/2665

**Comment by ChrisRackauckas** [comment]
Don't you just need to add the initializationprob call up here? https://github.com/SciML/DiffEqBase.jl/blob/master/src/solve.jl#L678

**Comment by AayushSabharwal** [comment]
Hmm yeah that does look better. I'll try that, thanks!

**Comment by AayushSabharwal** [comment]
Superseded by https://github.com/SciML/OrdinaryDiffEq.jl/pull/2314

**Pull request closed without merging**
