### PR TITLE
Perform step refactor for Tsit

### PR DESCRIPTION
**Pull request by ParamThakkar123**
## Checklist

- [X] Appropriate tests were added
- [X] Any code changes were done in a way that does not break public API
- [ ] All documentation related to code changes were updated
- [ ] The new code follows the
  [contributor guidelines](https://github.com/SciML/.github/blob/master/CONTRIBUTING.md), in particular the [SciML Style Guide](https://github.com/SciML/SciMLStyle) and
  [COLPRAC](https://github.com/SciML/COLPRAC).
- [X] Any new documentation only uses public API
  
## Additional context

solves a part of #233

### CODE REVIEW

**Comment by oscardssmith** [comment]
how does the performance compare?

**Comment by ChrisRackauckas** [comment]
Explicit RK is a bit tougher. It has a lot harder performance-wise. It needs a good understanding of https://github.com/SciML/OrdinaryDiffEq.jl/issues/233#issuecomment-2081665059

**Comment by ChrisRackauckas** [comment]
I don't understand the point of this PR. As mentioned in the other threads and the comment above, the general tableau for ERK methods is about feature-completeness and correctness of ExplicitRK and subsuming other RKs into that.

**Comment by ParamThakkar123** [comment]
> I don't understand the point of this PR. As mentioned in the other threads and the comment above, the general tableau for ERK methods is about feature-completeness and correctness of ExplicitRK and subsuming other RKs into that.

Actually, all I did here is refactor of perform_step implementations focusing only on the tsit solvers.  The Tsit tableau was implemented in the library for this solvers. So I just refactored it that way. Focusing only on this.

**Comment by ChrisRackauckas** [comment]
Yes, that does not make sense given ExplicitRK exists.

**Comment by ParamThakkar123** [comment]
> Yes, that does not make sense given ExplicitRK exists.

So should I be doing ExplicitRK first and then combining tsit into it ??

**Comment by ChrisRackauckas** [comment]
ExplicitRK exists and has a Tsit5 tableau already. Its mostly about feature-completeness and performance now.

**Comment by ParamThakkar123** [comment]
So what should be done further as far as this PR is concerned ?

**Comment by ParamThakkar123** [comment]
@ChrisRackauckas should I move on with the refactoring of ExplicitRK first ??

**Comment by ParamThakkar123** [comment]
> No it's already "refactored". It's about improving it and feature completing it. Testing it against the other implementations of RKs and making sure it floating point matches, and making sure default controller values are set appropriately.

Got it. Should I work towards feature completing it. What should be the first thing that should be done to start off with that ?

**Comment by ChrisRackauckas** [comment]
Run Tsit5 and the tableau form of Tsit5 and get the times array to match exactly. I think the controller params are probably the place to start.

**Comment by ParamThakkar123** [comment]
> Run Tsit5 and the tableau form of Tsit5 and get the times array to match exactly. I think the controller params are probably the place to start.

@ChrisRackauckas I ran the Tsit5 and its tableau form on a sample DE as follows : 
image

and the times arrays seem to match exactly

**Comment by ChrisRackauckas** [comment]
What about with stiffness detection and switching?

**Comment by ParamThakkar123** [comment]
> What about with stiffness detection and switching?

image

@ChrisRackauckas

**Comment by ChrisRackauckas** [comment]
I mean build an autoswitch alg that uses the ExplicitRK version, does that match the Tsit5 behavior?

**Pull request closed without merging**
