### PR TITLE
Fix `PIDController` when the error estimate is zero

### LINKED ISSUE #1703: `PIDController` needs an additional check to avoid dividing by zero
```julia
julia> using Pkg; Pkg.activate(temp=true); Pkg.add("OrdinaryDiffEq")

julia> using OrdinaryDiffEq

julia> function rhs!(du, u, p, t)
           du[1] = 1.0
       end
rhs! (generic function with 1 method)

julia> u0 = [0.0]
1-element Vector{Float64}:
 0.0

julia> ode = ODEProblem(rhs!, u0, (0.0, 5.0), nothing)
ODEProblem with uType Vector{Float64} and tType Float64. In-place: true
timespan: (0.0, 5.0)
u0: 1-element Vector{Float64}:
 0.0

julia> sol = solve(ode, RDPK3SpFSAL49());
┌ Warning: unlimited dt_factor
│   dt_factor = NaN
│   err1 = 7.793634568134567e13
│   err2 = Inf
│   err3 = Inf
│   beta1 = 0.38
│   beta2 = -0.18
│   beta3 = 0.01
│   k = 4
│   controller.err[1] = 7.793634568134567e13
│   controller.err[2] = Inf
│   controller.err[3] = Inf
└ @ OrdinaryDiffEq ~/.julia/packages/OrdinaryDiffEq/FhKjw/src/integrators/controllers.jl:272
┌ Warning: NaN dt detected. Likely a NaN value in the state, parameters, or derivative value caused this outcome.
└ @ SciMLBase ~/.julia/packages/SciMLBase/cGK2b/src/integrator_interface.jl:402
```

Reported by @efaulhaber

I will take care of this.

### PR DESCRIPTION
**Pull request by ranocha**
Closes #1703

### CODE REVIEW

**Comment by ranocha** [comment]
The buildkite failure seems to be unrelated: https://buildkite.com/julialang/ordinarydiffeq-dot-jl/builds/1196#018224c8-ce35-400d-83ab-b14d28360b89/419-1055

**Comment by ranocha** [comment]
bump

**Comment by ChrisRackauckas** [comment]
Yes unrelated.

**Comment by ChrisRackauckas** [comment]
@shashi please let's bump Metatheory.jl DocStringExtensions.

**Pull request merged**
