### PR TITLE
Error in Rodas3: Update rosenbrock_perform_step.jl

### PR DESCRIPTION
**Pull request by gstein3m**
Error in Rodas3

## Checklist

- [ ] Appropriate tests were added
- [ ] Any code changes were done in a way that does not break public API
- [ ] All documentation related to code changes were updated
- [ ] The new code follows the
  [contributor guidelines](https://github.com/SciML/.github/blob/master/CONTRIBUTING.md), in particular the [ScioML Style Guide](https://github.com/SciML/SciMLStyle) and
  [COLPRAC](https://github.com/SciML/COLPRAC).
- [ ] Any new documentation only uses public API

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Thanks! I am going to read back through the issues today and see where we are at.

@avik-pal do you know what's going on here? https://buildkite.com/julialang/ordinarydiffeq-dot-jl/builds/3001#018c5485-5141-49a5-b63f-aa558620356f

**Comment by avik-pal** [comment]
`autodiff = AutoFiniteDiff()`

**Comment by avik-pal** [comment]
The old API was dropped in the breaking change

**Comment by ChrisRackauckas** [comment]
okay that needs to be propagated up to OrdinaryDiffEq.jl.

**Pull request merged**
