### PR TITLE
Reduce number of calls in typed code

### PR DESCRIPTION
**Pull request by chriselrod**
Mostly this just makes Cthulhu look prettier by cutting down the number of branches.
Doesn't seem to help compile or runtime.

Co-authored-by: Yingbo Ma <mayingbo5@gmail.com>

### CODE REVIEW

**Review by YingboMa — APPROVED** [review]

**Comment by ChrisRackauckas** [comment]
Update the failing regression test by increasing the tolerance.

Though we need to fix the buildkite to not give us ARM. I don't know who added that to the ecosystem queue but that's the most breaking thing I've seen and it probably breaks every CI using that queue, so we should get that reversed.

**Comment by devmotion** [comment]
> Though we need to fix the buildkite to not give us ARM. I don't know who added that to the ecosystem queue but that's the most breaking thing I've seen and it probably breaks every CI using that queue, so we should get that reversed.

I noticed this as well, it broke eg also TuringTutorials (and hence I assume SciMLTutorials, SciMLBenchmarks etc are broken as well). We explicitly specified the desired architecture to fix it: https://github.com/TuringLang/TuringTutorials/pull/298 Probably a good thing to do anyway, but it would have been less inconvenient if aarch64 would have been opt-in at least initially.

**Comment by ChrisRackauckas** [comment]
The error here is that ARM doesn't allow closures. We shouldn't consider that a standard architecture for CI if that's true.

**Comment by devmotion** [comment]
The tutorials didn't even start running since one can't use bash (and probably other programs) on these machines, so I don't know if there are additional Julia-specific problems.

**Comment by ChrisRackauckas** [comment]
Rebase?

**Pull request closed without merging**
