### PR TITLE
work around FastBroadcast bugfix

### PR DESCRIPTION
**Pull request by oscardssmith**
hopefully this fixes CI. tests currently in progress locally.
## Checklist

- [ ] Appropriate tests were added
- [ ] Any code changes were done in a way that does not break public API
- [ ] All documentation related to code changes were updated
- [ ] The new code follows the
  [contributor guidelines](https://github.com/SciML/.github/blob/master/CONTRIBUTING.md), in particular the [SciML Style Guide](https://github.com/SciML/SciMLStyle) and
  [COLPRAC](https://github.com/SciML/COLPRAC).
- [ ] Any new documentation only uses public API

### CODE REVIEW

**Comment by oscardssmith** [comment]
oh, things are far more broken than we thought. The problem seems to be real and the fact that it broke when FastBroadcast changed seems to be entirely coincidental????

**Comment by oscardssmith** [comment]
So the problem is that `D[:,i]` is a length 8 vector, while u is a 4x2 matrix. So presumably at some time D changed from being matrix like to vector like but only in the in place version??

**Comment by oscardssmith** [comment]
Oh, this is very funny. version 0.3.0 of Fastbroadcast fixed a bug that this code was relying on. Previously it was allowing broadcasts between 4x2 matrices and length 8 vectors even though that isn't supposed to work.

**Comment by oscardssmith** [comment]
well this was very dumb. I think it should be fixed now.

**Review by ChrisRackauckas — APPROVED** [review]

**Comment by oscardssmith** [comment]
Let's see if https://github.com/YingboMa/FastBroadcast.jl/pull/62 fixed this

**Comment by oscardssmith** [comment]
Local testing shows it did, but I closed and opened before the registry was actually updated.

**Pull request merged**
