### PR TITLE
Downstream test and fix MTK by re-enabling autodiff in SciMLNLsolve

### PR DESCRIPTION
**Pull request by ChrisRackauckas**
Fixes https://github.com/SciML/ModelingToolkit.jl/issues/2012

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
@oscardssmith make note.

**Comment by oscardssmith** [comment]
Good catch.

**Comment by ChrisRackauckas** [comment]
@chriselrod looks like there was a regression in PolyesterWeave.jl where it no longer takes Integer but needs Int in some spot

**Comment by chriselrod** [comment]
That's what I get for not running downstream tests. @Krastanov, think you can fix this? https://buildkite.com/julialang/ordinarydiffeq-dot-jl/builds/1790#0185596c-f7d5-4364-988c-410cf30e74d8

**Comment by chriselrod** [comment]
@Krastanov, I think it's useful to still have some concept of per-machine maximum number of threads (i.e., just like the num cores) that does not get invalidated.

Polyester has a thread mask indicating which threads are occupied. For systems with less than 64 threads, that mask can be a single `UInt64`.
But for systems with more threads than this, it needs to use multiple `UInt64`s.

**Pull request merged**
