### PR TITLE
Add polyester threading option

### PR DESCRIPTION
**Pull request by chriselrod**
I need to add tests, but:
atbatchbruss

### CODE REVIEW

**Review by YingboMa — APPROVED** [review]
What a clever macro! LGTM

**Comment by utkarsh530** [comment]
Yeah, this will be able to enhance the multi-threading feature in Parallel Extrapolation Algorithms. Thank you, @chriselrod :-)

**Comment by ChrisRackauckas** [comment]
Multithreading tests had a failure: https://github.com/SciML/OrdinaryDiffEq.jl/pull/1421/checks?check_run_id=2656670038#step:6:346

**Comment by YingboMa** [comment]
Looks like a few missing updates for cache parameters.

**Review by utkarsh530 — APPROVED** [review]

**Pull request merged**
