### PR TITLE
use StaticW more often

### PR DESCRIPTION
**Pull request by oscardssmith**
as pointed out by @ChrisRackauckas in https://github.com/SciML/OrdinaryDiffEq.jl/pull/2291, we should at least try this for the non-Rosenbrock solvers.

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Needs tests

**Comment by oscardssmith** [comment]
Don't existing tests cover this? What additional test would you like to see?

**Comment by oscardssmith** [comment]
https://github.com/SciML/OrdinaryDiffEq.jl/blob/4fd5afb8b5b3a105103dcb6f2430acc75b67862d/test/interface/linear_solver_test.jl#L191 which we just added hits it.

**Comment by ChrisRackauckas** [comment]
Alright then merge if tests pass

**Comment by oscardssmith** [comment]
interesting... there is an explicit test that `calc_W` returns a `StaticArrays.LU` but I'm unclear why that would be tested...

**Comment by ChrisRackauckas** [comment]
Legacy. That can be removed if we see the Static operator is a faster approach

**Comment by oscardssmith** [comment]
test removed

**Pull request merged**
